import React, { createContext, useContext, useMemo } from 'react';
import { useSettings, SETTINGS_KEYS } from './settings';

const LanguageContext = createContext();

// Translation data
const translations = {
  en: {
    // General UI
    'home': 'Home',
    'cart': 'Cart',
    'messages': 'Messages',
    'orders': 'Orders',
    'settings': 'Settings',
    'notifications': 'Notifications',
    'search': 'Search',
    'back': 'Back',
    'continue': 'Continue',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'loading': 'Loading...',
    'ai_chat': 'AI Chat',
    'welcome_to_pharmai': 'Welcome to PharmAI!',
    'ai_assistant_description': 'I\'m here to help with general health information, product questions, and pharmacy services. Remember, I\'m not a substitute for professional medical advice.',
    'typing': 'Typing...',
    'online': 'Online',
    'clear_chat': 'Clear Chat',
    'ai_error_message': 'Sorry, I\'m having trouble connecting. Please try again later.',
    'ai_disclaimer': '⚠️ PharmAI provides general information only. Not medical advice. Consult professionals for health concerns.',
    'message': 'Message',
    'sent': 'Sent',
    'delivered': 'Delivered',
    'read': 'Read',
    'type_message': 'Type a message...',
    'send': 'Send',
    
    // Product/Shopping
    'add_to_cart': 'Add to Cart',
    'buy_now': 'Buy Now',
    'price': 'Price',
    'out_of_stock': 'Out of Stock',
    'in_stock': 'In Stock',
    'product_description': 'Product Description',
    'product_unavailable': 'Product unavailable. Please try again.',
    
    // Homepage
    'hello': 'Hello',
    'friend': 'Friend',
    'search_placeholder': 'Search drugs, pharmacies',
    'new_arrivals': 'New Arrivals',
    'popular_products': 'Popular Products',
    'all_new_products': 'All New Products',
    'load_more': 'Load more',
    'new': 'New',
    'close': 'Close',
    'please_sign_in': 'Please sign in',
    'your_pharmacy_location': 'Your pharmacy location',
    'location_services': 'Location services',
    'calculating_eta': 'Calculating ETA...',
    'fetching_location': 'Fetching location...',
    'nearest_pharmacy': 'nearest pharmacy',
    'to': 'to',
    
    // Info Cards
    'welcome_message': 'Welcome to PharmaSeA',
    'find_medicines': 'Find medicines near you',
    'fast_delivery': 'Fast & reliable delivery',
    'learn_more': 'Learn more',
    'get_started': 'Get started',
    'shop_now': 'Shop now',
    'order_now': 'Order now',
    'browse_catalog': 'Browse catalog',
    'special_offer': 'Special Offer',
    'limited_time': 'Limited time offer',
    
    // Orders page
    'orders_page_orders': 'Orders',
    'orders_all': 'All',
    'orders_pending': 'Pending',
    'orders_processing': 'Processing',
    'orders_fulfilled': 'Fulfilled',
    'orders_cancelled': 'Cancelled',
    'no_orders_yet': 'No orders yet.',
    'order_number': 'Order #',
    'orders_customer': 'Customer',
    'orders_items': 'Items',
    'orders_total': 'Total',
    'orders_status': 'Status',
    'orders_see_more': 'See more',
    'more_items': 'more',
    'reveal_number': 'Reveal Number',
    'please_sign_in_continue': 'Please sign in to continue',
    'sign_in_sign_up': 'Sign In / Sign Up',
    'qty': 'Qty',
    
    // Messages page
    'my_conversations': 'My\nConversations',
    'search_chats': 'Search chats',
    'no_conversations_yet': 'No conversations yet.',
    'no_messages_yet': 'No messages yet.',
    
    // Cart page
    'cart_page_cart': 'Cart',
    'your_cart_is_empty': 'Your cart is empty.',
    'cart_remove': 'Remove',
    'subtotal': 'Subtotal',
    'delivery_fee': 'Delivery Fee',
    'cart_page_total': 'Total',
    'proceed_to_checkout': 'Proceed to Checkout',
    'order_summary': 'Order Summary',
    'cart_items': 'Items',
    'delivery_details': 'Delivery Details',
    'delivery_address': 'Delivery Address',
    'phone_number': 'Phone Number',
    'email_optional': 'Email (Optional)',
    'enter_delivery_address': 'Enter delivery address',
    'enter_phone_number': 'Enter phone number',
    'enter_email_address': 'Enter email address',
    'use_current_location': 'Use current location',
    'continue_to_payment': 'Continue to Payment',
    'payment_method': 'Payment Method',
    'pay_on_delivery': 'Pay on Delivery',
    'pay_with_cash_delivery': 'Pay with cash when order arrives',
    'online_payment': 'Online Payment',
    'pay_with_card': 'Pay with card, bank transfer, or USSD',
    'pay_with_card_bank_ussd': 'Pay with card, bank transfer, or USSD',
    'pay_with_cash_on_delivery': 'Pay with cash when order arrives',
    'use_your_health_insurance': 'Use your health insurance',
    'pay_with_insurance': 'Pay with Insurance',
    'use_health_insurance': 'Use your health insurance',
    'coming_soon': 'Coming Soon',
    'total_amount': 'Total Amount',
    'pay_now': 'Pay Now',
    'place_order': 'Place Order',
    'decrease_quantity': 'Decrease quantity',
    'increase_quantity': 'Increase quantity',
    'order_placement_failed': 'Order placement failed',
    'order_placed_delivery': 'Order placed successfully! You\'ll pay on delivery.',
    'payment_successful': 'Payment successful! Your order has been placed.',
    'checkout_failed': 'Checkout failed. Please try again.',
    
    // Profile page
    'my_profile': 'My Profile',
    'pharmacy_profile': 'Pharmacy Profile', 
    'edit_profile': 'Edit Profile',
    'profile_edit': 'Edit',
    'profile_save': 'Save',
    'profile_cancel': 'Cancel',
    'profile_close': 'Close',
    'view': 'View',
    'open': 'Open',
    'name': 'Name',
    'phone_number_profile': 'Phone Number',
    'address_profile': 'Address',
    'password': 'Password',
    'items_in_cart': 'Items in Cart',
    'profile_page_active_chats': 'Active Chats',
    'saved_items': 'Saved Items',
    'drugs_bought': 'Drugs Bought',
    'all_drugs_bought': 'All Drugs Bought',
    'my_saved_items': 'My Saved Items',
    'saved_products': 'Products',
    'saved_vendors': 'Vendors',
    'no_products_saved': 'No products saved',
    'start_adding_products': 'Start adding products you like!',
    'no_vendors_bookmarked': 'No vendors bookmarked',
    'bookmark_vendors': 'Bookmark vendors you like!',
    'log_out': 'Log Out',
    'search_placeholder_profile': 'Search prescriptions, orders, drugs...',
    'prescriptions': 'Prescriptions',
    'orders_profile': 'Orders',
    'drugs': 'Drugs',
    'all_results': 'All',
    'times': 'times',
    'bought': 'bought',
    'no_search_results': 'No results found',
    'profile_try_different_search': 'Try a different search term',
    
    // Pharmacy-specific terms
    'add_product': 'Add Product',
    'bulk_upload': 'Bulk Upload',
    'download_report': 'Download report',
    'download_csv': 'Download CSV',
    'download_excel': 'Download Excel',
    'inventory': 'Inventory',
    'pharmacy_edit_product': 'Edit Product',
    'delete_product': 'Delete Product',
      'products_sold': 'Products Sold',
      'pharmacy_active_chats': 'Active Chats',
      'reviews': 'Reviews',
      
      // Products section translations
      'products_no_products_yet': 'No products yet. Use the buttons above to add or bulk\u2011upload.',
      'products_edit_product': 'Edit Product',
      'product_image': 'Product Image',
      'image_url_placeholder': 'Image URL (or choose file below)',
      'products_product_description': 'Product Description',
      'enter_product_description': 'Enter product description',
      'confirm_delete_product': 'Are you sure you want to delete this item?',
      'yes_delete': 'Yes, Delete',
      'products_delete': 'Delete',
      'products_log_out': 'Log Out',
      
      // Product Detail page translations
      'customer_reviews': 'Customer Reviews',
      'detail_no_reviews_yet': 'No reviews yet. Be the first to review!',
      'pharmacy_response': '{pharmacyName} Response',
      'detail_message_vendor': 'Message Vendor',
      'detail_call_to_order': 'Call to Order',
      'detail_your_name': 'Your Name',
      'detail_your_review_optional': 'Your review... (optional)',    // ProductDetail page
    'detail_back': 'Back',
    'detail_page_call_to_order': 'Call to Order',
    'detail_get_directions': 'Get Directions',
    'detail_category': 'Category',
    'detail_add_to_cart': 'Add to Cart',
    'detail_page_message_vendor': 'Message Vendor',
    'share_product': 'Share Product',
    'detail_close': 'Close',
    'detail_loading': 'Loading…',
    'detail_no_products_found': 'No products found.',
    'leave_a_review': 'Leave a Review',
    'detail_page_your_name': 'Your Name',
    'detail_page_your_review_optional': 'Your review... (optional)',
    'submit_review': 'Submit Review',
    'submitting': 'Submitting…',
    'detail_see_more': 'See more',
    'show_less': 'Show less',
    'products_in_category': 'Products in "{category}"',
    'eta_to_pharmacy': '{time} to {pharmacy}',
    'detail_calculating_eta': 'Calculating ETA...',
    'detail_fetching_location': 'Fetching location...',
    'shareable_link_copied': 'Shareable link copied to clipboard!',
    'copy_this_link': 'Copy this link:',
    'please_sign_in_wishlist': 'Please sign in to add items to your wishlist',
    'failed_update_wishlist': 'Failed to update wishlist. Please try again.',
    'detail_please_sign_in': 'Please sign in',
    'detail_product_unavailable': 'Product unavailable. Please try again.',
    'failed_add_to_cart': 'Failed to add to cart.',
    'reviews_section': 'Reviews',
    'detail_page_no_reviews_yet': 'No reviews yet. Be the first to review!',
    'helpful': 'Helpful',
    
    // VendorProfile page
    'vendor_profile': 'Vendor Profile',
    'products_by': 'Products by',
    'vendor': 'Vendor',
    'of': 'of',
    'no_products_found_search': 'No products found matching your search.',
    'vendor_no_products_yet': 'No products yet.',
    'customers_only_chat': 'Only customers can start a chat with a pharmacy.',
    'could_not_start_chat': 'Could not start chat thread.',
    'pharmacy_report': 'Pharmacy Report',
    'field': 'Field',
    'value': 'Value',
    'report_pharmacy': 'Pharmacy',
    'report_email': 'Email',
    'report_address': 'Address',
    'report_phone': 'Phone',
    'product_name': 'Product Name',
    'report_category': 'Category',
    'report_stock': 'Stock',
    'report_sku': 'SKU',
    'report_price': 'Price',
    'order_id': 'Order ID',
    'report_customer': 'Customer',
    'report_status': 'Status',
    'report_date': 'Date',
    'report_products': 'Products',
    'add_to_bookmarks': 'Add to bookmarks',
    'remove_from_bookmarks': 'Remove from bookmarks',
    'search_by_name_category_sku': 'Search by name, category, or SKU...',
    'view_results': 'View Results',
    'clear': 'Clear',
    
    // PharmacyMap page
    'nearby_pharmacies': 'Nearby Pharmacies',
    'pharmacies_found_near_you': '{count} found near you',
    'loading_location': 'Loading location...',
    'filter_pharmacies': 'Filter pharmacies',
    'pharmacies_found_near_you_detailed': '{count} pharmacies found near you',
    'your_location': 'Your location',
    'getting_your_location': 'Getting your location...',
    'location_access_needed': 'Location access needed',
    'allow_location_access_etas': 'Please allow location access for accurate ETAs',
    'enable_location_services': 'Enable location services to see nearby pharmacies',
    'search_pharmacies': 'Search pharmacies...',
    'no_pharmacies_found': 'No pharmacies found',
    'map_try_different_search': 'Try a different search term',
    'map_name': 'Name',
    'map_address': 'Address',
    'keyboard_navigation_hint': 'Use ↑↓ arrow keys to navigate, Enter to select, Esc to close',
    'distance': 'Distance',
    'map_all': 'All',
    'within_5km': 'Within 5km',
    'within_10km': 'Within 10km',
    'within_20km': 'Within 20km',
    'you_are_here': 'You are here',
    'pharmacy_locations': 'Pharmacy Locations',
    'pharmacies_sorted_by_distance': '{count} pharmacies • Sorted by distance',
    'map_pharmacy': 'Pharmacy',
    'selected': 'Selected',
    'calculating': 'Calculating...',
    'closest': 'Closest',
    'get_directions': 'Get Directions',
    'call_pharmacy': 'Call pharmacy',
    'view_products': 'View Products',
    'search_results': 'Search Results',
    'all_pharmacies': 'All Pharmacies',
    'pharmacies_found_count': '{count} found',
    'no_pharmacies_found_search': 'No pharmacies found matching your search',
    'no_pharmacies_found_general': 'No pharmacies found',
    'try_adjusting_search': 'Try adjusting your search terms',
    'try_adjusting_location': 'Try adjusting your location or check back later',
    'clear_search': 'Clear search',

    // ChatThread page
    'today': 'Today',
    'yesterday': 'Yesterday',
    'chat_sent': 'Sent',
    'chat_delivered': 'Delivered',
    'chat_read': 'Read',
    'chat_customer': 'Customer',
    'chat_pharmacy': 'Pharmacy',
    'prescription_created': 'A new prescription has been created.',
    'drug_inquiry': 'I want to know more about this drug {productName}{priceText}.',
    'chat_call': 'Call',
    'call_pharmacy_title': 'Call {pharmacy}',
    'no_phone_number': 'No phone number',
    'actions': 'Actions',
    'create_prescription': 'Create Prescription',
    'view_prescription_history': 'View Prescription History',
    'load_more_messages': 'Load {count} more messages',
    'start_conversation': 'Start your conversation',
    'message_placeholder': 'Message',
    'attachments_coming_soon': 'Attachments coming soon',

    // Dashboard page
    'my_dashboard': 'My Dashboard',
    'overview': 'Overview',
    'top_products': 'Top Products',
    'best_sellers': 'Best Sellers',
    'no_sales_data': 'No sales data yet',
    'start_selling_message': 'Start selling products to see your top performers',
    'units_sold': '{count} units sold',
    'units': 'units',
    'total_products': 'Total Products',
    'total_orders': 'Total Orders',
    'total_revenue': 'Total Revenue',
    'active_customers': 'Active Customers',
    'this_month': 'This Month',
    'avg_order_value': 'Avg Order Value',
    'pending_orders': 'Pending Orders',
    'awaiting': 'Awaiting',
    'low_stock_items': 'Low Stock Items',
    'need_restock': 'Need Restock',
    'orders_this_month': 'Orders This Month',
    'no_comparison': 'No comparison',
    'pending_reviews': 'Pending Reviews',
    'need_response': 'Need Response',
    'recent_reviews': 'Recent Reviews',
    'last_24h': 'Last 24h',
    'low_stock_alert': 'Low Stock Alert',
    'items_need_restocking': '{count} item{plural} need restocking',
    'inventory_tip': 'Check your inventory to avoid running out of popular products',
    
    // Dashboard Components
    'recent_messages': 'Recent Messages',
    'no_recent_messages': 'No recent messages.',
    'no_recent_reviews': 'No recent reviews',
    'new_reviews_appear_here': 'New customer reviews will appear here',
    'dashboard_view_all': 'View All',
    'by_customer': 'by {customerName}',
    'needs_response': 'Needs Response',
    'view_more_reviews': 'View {count} more review{plural}',
    'revenue_analytics': 'Revenue Analytics',
    'by_month': 'By Month',
    'by_year': 'By Year',
    'month_number': 'Month {number}',
    'no_revenue_data': 'No revenue data available',
    'start_selling_revenue': 'Start making sales to see your revenue analytics',
    'best_performing_period': 'Best Performing {period}',
    'month_label': 'Month',
    'year_label': 'Year',
    'sales_trends': 'Sales Trends',
    'last_6_months': 'Last 6 months',
    'no_sales_trend_data': 'No sales trend data.',
    'orders_count': '{count} order{plural}',
    
    // Reviews Management
    'reviews_management': 'Reviews Management',
    'filters_sort': 'Filters & Sort',
    'total_reviews': 'Total Reviews',
    'responded': 'Responded',
    'avg_rating': 'Avg Rating',
    'positive_reviews': 'Positive (4+ ⭐)',
    'reviews_product': 'Product',
    'all_products': 'All Products',
    'sort_by': 'Sort By',
    'newest_first': 'Newest First',
    'oldest_first': 'Oldest First',
    'highest_rating': 'Highest Rating',
    'lowest_rating': 'Lowest Rating',
    'filter_by': 'Filter By',
    'all_reviews': 'All Reviews',
    'positive_4_stars': 'Positive (4+ stars)',
    'negative_1_2_stars': 'Negative (1-2 stars)',
    'no_reviews_found': 'No reviews found',
    'no_reviews_yet_message': "You don't have any reviews yet. Encourage customers to leave reviews by providing excellent service and follow-up communication!",
    'no_reviews_match_filters': "No reviews match your current filters. Try adjusting your search criteria.",
    'medicine': 'Medicine',
    'reviewed_by': 'Reviewed by',
    'verified': 'Verified',
    'people_found_helpful': '{count} people found this helpful',
    'your_response': 'Your Response',
    'cancel_response': 'Cancel Response',
    'respond_to_review': 'Respond to Review',
    'write_thoughtful_response': 'Write a thoughtful response to this review...',
    'submit_response': 'Submit Response',
    'response_submitted_success': 'Response submitted successfully!',
    'response_submit_failed': 'Failed to submit response. Please try again.',
    'reviews_loading_reviews': 'Loading your reviews...',
    'loading_please_wait': 'Please wait while we fetch your data',
    
    // My Prescriptions Section
    'my_prescriptions': 'My Prescriptions',
    'add_to_calendar': 'Add to Calendar',
    'prescriptions_no_prescriptions_found': 'No prescriptions found.',
    'prescriptions_see_more_count': 'See more ({count})',
    'prescriptions_see_less': 'See less',
    'time_to_take_medicine': 'Time to take {drugName}',
    'take_medicine': 'Take {drugName}',
    'dosage_frequency': 'Dosage: {dosage} ({frequency})',
    
    // Profile sections
    'my_activity': 'My Activity',
    'profile_active_chats': 'Active Chats', 
    'storefront_preview': 'Storefront Preview',
    'profile_inventory': 'Inventory',
    'profile_products_sold': 'Products Sold',
    
    // Pharmacy-specific terms
    
    // Settings
    'settings_general': 'General',
    'settings_appearance': 'Appearance',
    'settings_language_region': 'Language & Region',
    'settings_privacy_security': 'Privacy & Security',
    'settings_accessibility': 'Accessibility',
    'swipe_navigation': 'Swipe Navigation',
    'data_saver_mode': 'Data Saver Mode',
    'read_receipts': 'Read Receipts',
    'theme': 'Theme',
    'font_size': 'Font Size',
    'app_language': 'App Language'
  },
  
  yo: {
    // General UI (Yoruba)
    'home': 'Ile',
    'yo_cart': 'Agolo',
    'messages': 'Ifiranše',
    'yo_orders': 'Awọn ibere',
    'settings': 'Eto',
    'notifications': 'Iwifun',
    'search': 'Wa',
    'back': 'Pada',
    'continue': 'Tẹsiwaju',
    'yo_save': 'Tọju',
    'yo_cancel': 'Fagile',
    'yo_delete': 'Pa rẹ',
    'yo_edit': 'Ṣatunkọ',
    'yo_loading': 'N gbe...',
    'profile': 'Profaili',
    
    // Chat
    'message': 'Ifiranşe',
    'sent': 'Ti fi ranşe',
    'delivered': 'Ti gba',
    'read': 'Ti ka',
    'type_message': 'Kọ ifiranše...',
    'send': 'Fi ranše',
    
    // Homepage (Yoruba)
    'hello': 'Bawo',
    'friend': 'Ore',
    'search_placeholder': 'Wa oogun, ile oogun',
    'new_arrivals': 'Awọn tuntun',
    'yo_view_all': 'wo gbogbo',
    'popular_products': 'Awọn oogun olokiki',
    'all_new_products': 'Gbogbo oogun tuntun',
    'load_more': 'Gbe siwaju',
    'new': 'Tuntun',
    'yo_close': 'Ti',
    'yo_please_sign_in': 'Jọwọ wọle',
    'your_pharmacy_location': 'Ipo ile oogun rẹ',
    'location_services': 'Awọn iṣẹ ipo',
    'yo_calculating_eta': 'N ṣe iṣiro akoko...',
    'yo_fetching_location': 'N gba ipo...',
    'nearest_pharmacy': 'ile oogun to sunmọ',
    'to': 'si',
    
    // Info Cards (Yoruba)
    'welcome_message': 'Kaabo si PharmaSeA',
    'find_medicines': 'Wa awọn oogun to wa nitosi rẹ',
    'fast_delivery': 'Ifijiṣẹ to yara ati to gbẹkẹle',
    'learn_more': 'Kọ siwaju si',
    'get_started': 'Bẹrẹ',
    'shop_now': 'Ra ni bayi',
    'order_now': 'Bere ni bayi',
    'browse_catalog': 'Wo awọn oogun wa',
    'special_offer': 'Ipese Pataki',
    'limited_time': 'Ipese akoko die',
    
    // Orders page (Yoruba)
    'orders': 'Awọn ibere',
    'all': 'Gbogbo',
    'pending': 'Ti nduro',
    'processing': 'N ṣiṣẹ',
    'fulfilled': 'Ti pari',
    'cancelled': 'Ti fagile',
    'no_orders_yet': 'Ko si ibere kankan sibẹ.',
    'order_number': 'Ibere #',
    'orders_customer': 'Onibara',
    'orders_items': 'Awọn nkan',
    'orders_total': 'Lapapọ',
    'orders_status': 'Ipo',
    'orders_see_more': 'Wo siwaju si',
    'orders_see_less': 'Wo diẹ kere si',
    'more_items': 'siwaju si',
    'reveal_number': 'Fi nọmba han',
    'please_sign_in_continue': 'Jọwọ wọle lati tẹsiwaju',
    'sign_in_sign_up': 'Wọle / Forukọsilẹ',
    'qty': 'Iye',
    
    // Messages page (Yoruba)
    'my_conversations': 'Awọn\nIforọranṣẹ Mi',
    'search_chats': 'Wa awọn iforọranṣẹ',
    'no_conversations_yet': 'Ko si iforọranṣẹ kankan sibẹ.',
    'no_messages_yet': 'Ko si ifiranṣẹ kankan sibẹ.',
    
    // Cart page (Yoruba)
    'cart': 'Agolo',
    'your_cart_is_empty': 'Agolo rẹ ko ni nkankan.',
    'remove': 'Yo kuro',
    'cart_subtotal': 'Apapọ kekere',
    'delivery_fee': 'Owo ifijiṣẹ',
    'cart_total': 'Lapapọ',
    'proceed_to_checkout': 'Tẹsiwaju si isanwo',
    'order_summary': 'Akopọ ibere',
    'cart_items': 'Awọn nkan',
    'delivery_details': 'Awọn alaye ifijiṣẹ',
    'delivery_address': 'Adiresi ifijiṣẹ',
    'phone_number': 'Nọmba foonu',
    'email_optional': 'Imeeli (Ti o ba fẹ)',
    'enter_delivery_address': 'Tẹ adiresi ifijiṣẹ',
    'enter_phone_number': 'Tẹ nọmba foonu',
    'enter_email_address': 'Tẹ adiresi imeeli',
    'use_current_location': 'Lo ipo oni bayi',
    'continue_to_payment': 'Tẹsiwaju si isanwo',
    'payment_method': 'Ona isanwo',
    'pay_on_delivery': 'San nigba ifijiṣẹ',
    'pay_with_cash_delivery': 'San pẹlu owo nigba ti ibere ba de',
    'online_payment': 'Isanwo ori ayelujara',
    'pay_with_card': 'San pẹlu kaadi, gbigbe owo banki, tabi USSD',
    'pay_with_card_bank_ussd': 'San pẹlu kaadi, gbigbe owo banki, tabi USSD',
    'pay_with_cash_on_delivery': 'San pẹlu owo nigba ti ibere ba de',
    'use_your_health_insurance': 'Lo idaabobo ilera rẹ',
    'pay_with_insurance': 'San pẹlu idaabobo',
    'use_health_insurance': 'Lo idaabobo ilera rẹ',
    'coming_soon': 'O nbọ laipẹ',
    'total_amount': 'Iye lapapọ',
    'pay_now': 'San ni bayi',
    'place_order': 'Gbe ibere kalẹ',
    'decrease_quantity': 'Din iye ku',
    'increase_quantity': 'Pọ si iye',
    'order_placement_failed': 'Gbigbe ibere kalẹ kuna',
    'order_placed_delivery': 'A ti gbe ibere kalẹ ni aṣeyọri! O ma san nigba ifijiṣẹ.',
    'payment_successful': 'Isanwo aṣeyọri! A ti gbe ibere rẹ kalẹ.',
    'checkout_failed': 'Isanwo kuna. Jọwọ gbiyanju lẹẹkansi.',
    
    // Profile page (Yoruba)
    'my_profile': 'Profaili Mi',
    'pharmacy_profile': 'Profaili Ile-oogun',
    'edit_profile': 'Ṣatunṣe Profaili',
    'profile_edit': 'Ṣatunṣe',
    'profile_save': 'Fi pamọ',
    'profile_cancel': 'Fagilee',
    'profile_close': 'Ti',
    'view': 'Wo',
    'open': 'Ṣi',
    'name': 'Orukọ',
    'phone_number_profile': 'Nọmba Foonu',
    'address_profile': 'Adiresi',
    'password': 'Ọrọ aṣina',
    'items_in_cart': 'Awọn nkan ninu agolo',
    'profile_active_chats': 'Awọn ibaraẹnisọrọ ti nṣiṣẹ',
    'saved_items': 'Awọn nkan ti a fi pamọ',
    'drugs_bought': 'Awọn oogun ti a ra',
    'all_drugs_bought': 'Gbogbo awọn oogun ti a ra',
    'my_saved_items': 'Awọn nkan ti mo fi pamọ',
    'products': 'Awọn ọja',
    'vendors': 'Awọn olutaja',
    'no_products_saved': 'Ko si ọja ti a fi pamọ',
    'start_adding_products': 'Bẹrẹ fifi awọn ọja ti o fẹran si!',
    'no_vendors_bookmarked': 'Ko si olutaja ti a ṣaami',
    'bookmark_vendors': 'Ṣe aami awọn olutaja ti o fẹran!',
    'log_out': 'Jade',
    'search_placeholder_profile': 'Wa awọn atọrọ, awọn ibere, oogun...',
    'prescriptions': 'Awọn atọrọ',
    'orders_profile': 'Awọn ibere',
    'drugs': 'Awọn oogun',
    'all_results': 'Gbogbo',
    'times': 'igba',
    'bought': 'ti a ra',
    'no_search_results': 'Ko si abajade',
    'try_different_search': 'Gbiyanju ọrọ wiwa miiran',
    
    // ProductDetail page (Yoruba)
    'detail_back': 'Pada',
    'detail_call_to_order': 'Pe lati gbe ibere',
    'detail_get_directions': 'Gba itọsọna',
    'detail_category': 'Isọri',
    'detail_add_to_cart': 'Fi si agolo',
    'detail_message_vendor': 'Firanṣẹ si olutaja',
    'share_product': 'Pin ọja',
    'detail_close': 'Ti',
    'detail_loading': 'Ngbigba...',
    'no_products_found': 'Ko si ọja ti a ri.',
    'leave_a_review': 'Fi atunyẹwo silẹ',
    'detail_your_name': 'Orukọ rẹ',
    'detail_your_review_optional': 'Atunyẹwo rẹ... (ti o ba fẹ)',
    'submit_review': 'Fi atunyẹwo ranṣẹ',
    'submitting': 'Nfiranṣẹ...',
    'see_more': 'Wo siwaju si',
    'show_less': 'Fi diẹ han',
    'products_in_category': 'Awọn ọja ninu "{category}"',
    'eta_to_pharmacy': '{time} si {pharmacy}',
    'calculating_eta': 'Nṣiro akoko...',
    'fetching_location': 'Ngba ipo...',
    'shareable_link_copied': 'A ti daakọ ọna asopọ pinpin si clipboard!',
    'copy_this_link': 'Daakọ ọna asopọ yii:',
    'please_sign_in_wishlist': 'Jọwọ wọle lati fi awọn nkan si atokọ ifẹ rẹ',
    'failed_update_wishlist': 'Kuna lati ṣe imudojuiwọn atokọ ifẹ. Jọwọ gbiyanju lẹẹkansi.',
    'please_sign_in': 'Jọwọ wọle',
    'product_unavailable': 'Ọja ko si. Jọwọ gbiyanju lẹẹkansi.',
    'failed_add_to_cart': 'Kuna lati fi si agolo.',
    'reviews_section': 'Awọn atunyẹwo',
    'no_reviews_yet': 'Ko si atunyẹwo sibẹ. Jẹ ẹni akọkọ lati ṣe atunyẹwo!',
    'helpful': 'To wulo',
    
    // VendorProfile page (Yoruba)
    'vendor_profile': 'Profaili Olutaja',
    'products_by': 'Awọn ọja nipasẹ',
    'vendor': 'Olutaja',
    'of': 'ninu',
    'no_products_found_search': 'Ko si ọja ti a ri ti o baamu wiwa rẹ.',
    'vendor_no_products_yet': 'Ko si ọja sibẹ.',
    'customers_only_chat': 'Awọn alabara nikan lo le bẹrẹ ibaraẹnisọrọ pẹlu ile-oogun.',
    'could_not_start_chat': 'Ko le bẹrẹ okun ibaraẹnisọrọ.',
    'pharmacy_report': 'Ijabọ ile-oogun',
    'field': 'Aaye',
    'value': 'Iye',
    'pharmacy': 'Ile-oogun',
    'email': 'Imeeli',
    'address': 'Adiresi',
    'phone': 'Foonu',
    'product_name': 'Orukọ ọja',
    'category': 'Isọri',
    'stock': 'Ipamọ',
    'sku': 'SKU',
    'price': 'Idiyele',
    'order_id': 'ID ibere',
    'vendor_customer': 'Alabara',
    'vendor_status': 'Ipo',
    'date': 'Ọjọ',
    'vendor_products': 'Awọn ọja',
    'add_to_bookmarks': 'Fi si awọn aami iwe',
    'remove_from_bookmarks': 'Yo kuro ninu awọn aami iwe',
    'search_by_name_category_sku': 'Wa nipasẹ orukọ, isọri, tabi SKU...',
    'view_results': 'Wo awọn abajade',
    'clear': 'Nu',
    
    // PharmacyMap page (Yoruba)
    'nearby_pharmacies': 'Awọn Ile-oogun Nitosi',
    'pharmacies_found_near_you': '{count} ti a ri nitosi rẹ',
    'loading_location': 'N gba ipo...',
    'filter_pharmacies': 'Ṣe ajọ awọn ile-oogun',
    'pharmacies_found_near_you_detailed': 'Awọn ile-oogun {count} ti a ri nitosi rẹ',
    'your_location': 'Ipo rẹ',
    'getting_your_location': 'N gba ipo rẹ...',
    'location_access_needed': 'A nilo iwọle si ipo',
    'allow_location_access_etas': 'Jọwọ gba iwọle si ipo fun awọn akoko to peye',
    'enable_location_services': 'Mu awọn iṣẹ ipo ṣiṣẹ lati ri awọn ile-oogun nitosi',
    'search_pharmacies': 'Wa awọn ile-oogun...',
    'no_pharmacies_found': 'Ko ri ile-oogun kankan',
    'map_try_different_search': 'Gbiyanju ọrọ wiwa miiran',
    'map_name': 'Orukọ',
    'map_address': 'Adiresi',
    'keyboard_navigation_hint': 'Lo awọn bọtini ↑↓ lati lilọ, Enter lati yan, Esc lati ti',
    'distance': 'Ijinna',
    'map_all': 'Gbogbo',
    'within_5km': 'Laarin 5km',
    'within_10km': 'Laarin 10km',
    'within_20km': 'Laarin 20km',
    'you_are_here': 'O wa nibi',
    'pharmacy_locations': 'Awọn Ipo Ile-oogun',
    'pharmacies_sorted_by_distance': 'Awọn ile-oogun {count} • Ti a to ni ọna ijinna',
    'map_pharmacy': 'Ile-oogun',
    'selected': 'Ti a yan',
    'calculating': 'N ṣe iṣiro...',
    'closest': 'Ti o sunmọ julọ',
    'get_directions': 'Gba Itọsọna',
    'map_call': 'Pe',
    'call_pharmacy': 'Pe ile-oogun',
    'view_products': 'Wo Awọn Ọja',
    'search_results': 'Awọn Abajade Wiwa',
    'all_pharmacies': 'Gbogbo Awọn Ile-oogun',
    'pharmacies_found_count': '{count} ti a ri',
    'no_pharmacies_found_search': 'Ko ri ile-oogun ti o baamu wiwa rẹ',
    'no_pharmacies_found_general': 'Ko ri ile-oogun kankan',
    'try_adjusting_search': 'Gbiyanju ṣe atunṣe awọn ọrọ wiwa rẹ',
    'try_adjusting_location': 'Gbiyanju ṣe atunṣe ipo rẹ tabi padanu nigbamii',
    'clear_search': 'Nu wiwa',

    // ChatThread page (Yoruba)
    'today': 'Oni',
    'yesterday': 'Ana',
    'chat_sent': 'Ti fi ranṣẹ',
    'chat_delivered': 'Ti gba',
    'chat_read': 'Ti ka',
    'chat_customer': 'Alabara',
    'chat_pharmacy': 'Ile-oogun',
    'prescription_created': 'A ti ṣe iwe-aṣẹ oogun tuntun.',
    'drug_inquiry': 'Mo fẹ mọ diẹ sii nipa oogun yii {productName}{priceText}.',
    'chat_call': 'Pe',
    'call_pharmacy_title': 'Pe {pharmacy}',
    'no_phone_number': 'Ko si nọmba foonu',
    'actions': 'Awọn iṣe',
    'create_prescription': 'Ṣe Iwe-aṣẹ Oogun',
    'view_prescription_history': 'Wo Itan Iwe-aṣẹ Oogun',
    'load_more_messages': 'Gbe awọn ifiranṣẹ {count} sii',
    'start_conversation': 'Bẹrẹ ibaraẹnisọrọ rẹ',
    'message_placeholder': 'Ifiranṣẹ',
    'attachments_coming_soon': 'Awọn aṣopọ n bọ laipe',

    // Dashboard page (Yoruba)
    'my_dashboard': 'Pátákó Mi',
    'overview': 'Akopọ',
    'top_products': 'Awọn Ọja Giga',
    'best_sellers': 'Awọn Ti O Ta Julọ',
    'no_sales_data': 'Ko si data tita sibẹ',
    'start_selling_message': 'Bẹrẹ tita awọn ọja lati ri awọn ti o ṣe daradara',
    'units_sold': 'Awọn ẹya {count} ti a ta',
    'units': 'awọn ẹya',
    'total_products': 'Lapapọ Awọn Ọja',
    'total_orders': 'Lapapọ Awọn Ibere',
    'total_revenue': 'Lapapọ Owo Wiwọle',
    'active_customers': 'Awọn Alabara Ti Nṣiṣẹ',
    'this_month': 'Oṣu Yii',
    'avg_order_value': 'Idiye Ibere Aarin',
    'pending_orders': 'Awọn Ibere Ti Nduro',
    'awaiting': 'N duro',
    'low_stock_items': 'Awọn Ọja Ti Ko To',
    'need_restock': 'Nilo Ṣe Ipamọ',
    'orders_this_month': 'Awọn Ibere Oṣu Yii',
    'no_comparison': 'Ko si afiwe',
    'pending_reviews': 'Awọn Atunyẹwo Ti Nduro',
    'need_response': 'Nilo Idahun',
    'recent_reviews': 'Awọn Atunyẹwo Aipẹ',
    'last_24h': 'Wakati 24 sẹhin',
    'low_stock_alert': 'Ikilọ Ipamọ Kekere',
    'items_need_restocking': 'Awọn nkan {count} nilo atunkọ ipamọ',
    'inventory_tip': 'Ṣayẹwo ipamọ rẹ lati yago fun sisọnu awọn ọja olokiki',
    
    // Dashboard Components (Yoruba)
    'recent_messages': 'Awọn Ifiranṣẹ Aipẹ',
    'no_recent_messages': 'Ko si awọn ifiranṣẹ aipẹ.',
    'no_recent_reviews': 'Ko si awọn atunyẹwo aipẹ',
    'new_reviews_appear_here': 'Awọn atunyẹwo alabara tuntun yoo han nibi',
    'view_all': 'Wo Gbogbo',
    'by_customer': 'nipasẹ {customerName}',
    'needs_response': 'Nilo Idahun',
    'view_more_reviews': 'Wo awọn atunyẹwo {count} sii',
    'revenue_analytics': 'Itupalẹ Owo Wiwọle',
    'dashboard_total': 'Lapapọ',
    'by_month': 'Nipasẹ Oṣu',
    'by_year': 'Nipasẹ Ọdun',
    'month_number': 'Oṣu {number}',
    'no_revenue_data': 'Ko si data owo wiwọle',
    'start_selling_revenue': 'Bẹrẹ tita lati ri itupalẹ owo wiwọle rẹ',
    'best_performing_period': 'Asiko Ti O Ṣe Daradara Julọ {period}',
    'month_label': 'Oṣu',
    'year_label': 'Ọdun',
    'sales_trends': 'Awọn Ilọsiwaju Tita',
    'last_6_months': 'Oṣu 6 sẹhin',
    'no_sales_trend_data': 'Ko si data ilọsiwaju tita.',
    'orders_count': 'Awọn ibere {count}',
    
    // Reviews Management (Yoruba)
    'reviews_management': 'Iṣakoso Awọn Atunyẹwo',
    'filters_sort': 'Awọn Àṣẹ ati Tito',
    'total_reviews': 'Lapapọ Awọn Atunyẹwo',
    'responded': 'Ti Dahun',
    'avg_rating': 'Iwọn Aarin',
    'positive_reviews': 'Rere (4+ ⭐)',
    'product': 'Ọja',
    'all_products': 'Gbogbo Awọn Ọja',
    'sort_by': 'To Nipasẹ',
    'newest_first': 'Tuntun Ni Akọkọ',
    'oldest_first': 'Atijọ Ni Akọkọ',
    'highest_rating': 'Iwọn Giga Julọ',
    'lowest_rating': 'Iwọn Kekere Julọ',
    'filter_by': 'Àṣẹ Nipasẹ',
    'all_reviews': 'Gbogbo Awọn Atunyẹwo',
    'positive_4_stars': 'Rere (4+ irawo)',
    'negative_1_2_stars': 'Buburu (1-2 irawo)',
    'no_reviews_found': 'Ko ri atunyẹwo kankan',
    'no_reviews_yet_message': 'O ko ni awọn atunyẹwo sibẹ. Gba awọn alabara niyanju lati fi awọn atunyẹwo silẹ nipa ipese iṣẹ to dara ati ibaraẹnisọrọ atẹle!',
    'no_reviews_match_filters': 'Ko si atunyẹwo ti o baamu awọn àṣẹ rẹ lọwọlọwọ. Gbiyanju ṣatunṣe awọn ami wiwa rẹ.',
    'medicine': 'Oogun',
    'reviewed_by': 'Ti a ṣe atunyẹwo nipasẹ',
    'verified': 'Ti a Ṣe Idaniloju',
    'people_found_helpful': 'Awọn eniyan {count} ri eyi ni iranlọwọ',
    'your_response': 'Idahun Rẹ',
    'cancel_response': 'Pa Idahun Rẹ',
    'respond_to_review': 'Dahun si Atunyẹwo',
    'write_thoughtful_response': 'Kọ idahun ti o ni ero si atunyẹwo yii...',
    'submit_response': 'Fi Idahun Ranṣẹ',
    'response_submitted_success': 'Idahun ti fi ranṣẹ ni aṣeyọri!',
    'response_submit_failed': 'Kuna lati fi idahun ranṣẹ. Jọwọ gbiyanju lẹẹkansi.',
    'loading_reviews': 'Ngba awọn atunyẹwo rẹ...',
    'loading_please_wait': 'Jọwọ duro nigba ti a n gba data rẹ',
    
    // My Prescriptions Section (Yoruba)
    'my_prescriptions': 'Awọn Iwe-aṣẹ Oogun Mi',
    'add_to_calendar': 'Fi si Kalenda',
    'prescriptions_no_prescriptions_found': 'Ko ri iwe-aṣẹ oogun kankan.',
    'prescriptions_see_more_count': 'Wo sii ({count})',
    'prescriptions_see_less': 'Wo kere',
    'time_to_take_medicine': 'Akoko lati mu {drugName}',
    'take_medicine': 'Mu {drugName}',
    'dosage_frequency': 'Iwọn: {dosage} ({frequency})',
    
    // Profile sections (Yoruba)
    'my_activity': 'Iṣẹ Mi',
    'profile_active_chats': 'Awọn Ibaraẹnisọrọ Ti Nṣiṣẹ',
    'storefront_preview': 'Iwoye Ile-itaja',
    'profile_inventory': 'Ipamọ',
    'profile_products_sold': 'Awọn Ọja Ti A Ta',
    
    // Pharmacy-specific terms (Yoruba)
    'add_product': 'Fi ọja kun',
    'bulk_upload': 'Gbigbe ọpọlọpọ',
    'download_report': 'Gba ijabọ',
    'download_csv': 'Gba CSV',
    'download_excel': 'Gba Excel',
    'inventory': 'Ibi ipamọ ọja',
    'edit_product': 'Ṣatunṣe ọja',
    'delete_product': 'Pa ọja rẹ',
      'products_sold': 'Awọn ọja ti a ta',
      'active_chats': 'Awọn ibaraẹnisọrọ ti nṣiṣẹ',
      'reviews': 'Awọn atunyẹwo',
      
      // Products section translations (Yoruba)
      'products_no_products_yet': 'Ko si ọja sibẹsibẹ. Lo awọn bọtini ti o wa loke lati ṣafikun tabi gbé-gbe soke.',
      'products_edit_product': 'Ṣatunṣe Ọja',
      'product_image': 'Aworan Ọja',
      'image_url_placeholder': 'URL aworan (tabi yan faili ti o wa nisalẹ)',
      'products_product_description': 'Apejuwe Ọja',
      'enter_product_description': 'Tẹ apejuwe ọja sii',
      'confirm_delete_product': 'Ṣe o da ọ loju pe o fẹ pa nkan yii rẹ?',
      
      // Product Detail page translations (Yoruba)
      'customer_reviews': 'Awọn Atunyẹwo Alabara',
      'loading_reviews': 'N gba awọn atunyẹwo…',
      'no_reviews_yet': 'Ko si atunyẹwo sibẹ. Jẹ ki o jẹ ọkọ akoko lati ṣe atunyẹwo!',
      'pharmacy_response': 'Idahun {pharmacyName}',
      'detail_message_vendor': 'Ranṣẹ si Olutasọja',
      'detail_call_to_order': 'Pe lati Bẹẹrẹ',
      'your_name': 'Oruko Rẹ',
    'language_region': 'Ede & Agbegbe',
    'privacy_security': 'Aṣiri & Aabo',
    'accessibility': 'Iwọle',
    'swipe_navigation': 'Lilọ pẹlu fifọ',
    'data_saver_mode': 'Ipo itọju data',
    'read_receipts': 'Iwe eriwo kika',
    'theme': 'Koko',
    'font_size': 'Iwọn lẹta',
    'app_language': 'Ede ohun elo'
  },
  
  ha: {
    // General UI (Hausa)
    'home': 'Gida',
    'cart': 'Kaya',
    'messages': 'Saƙonni',
    'orders': 'Oda',
    'settings': 'Saiti',
    'notifications': 'Sanarwa',
    'search': 'Nema',
    'back': 'Baya',
    'continue': 'Ci gaba',
    'save': 'Ajiye',
    'cancel': 'Soke',
    'delete': 'Share',
    'edit': 'Gyara',
    'loading': 'Ana lodawa...',
    'profile': 'Bayanan martaba',
    
    // Product/Shopping (Hausa)
    'add_to_cart': 'Saka cikin kaya',
    'buy_now': 'Saya yanzu',
    'shopping_price': 'Farashi',
    'out_of_stock': 'Ba a kantin ba',
    'in_stock': 'A wanzu',
    'product_description': 'Bayanin kaya',
    'product_unavailable': 'Kaya ba ya samuwa. Ka sake gwadawa.',
    
    // Homepage (Hausa)
    'hello': 'Sannu',
    'friend': 'Aboki',
    'search_placeholder': 'Nema magunguna, kantin magani',
    'new_arrivals': 'Sababbin abubuwa',
    'view_all': 'dubi duka',
    'popular_products': 'Shahararrun magunguna',
    'all_new_products': 'Dukan sababbin magunguna',
    'load_more': 'Dauko kari',
    'new': 'Sabon',
    'close': 'Rufe',
    'please_sign_in': 'Ka shigar da sunan',
    'your_pharmacy_location': 'Wurin kantin maganin ku',
    'location_services': 'Sabis na wuri',
    'calculating_eta': 'Ana lissafa lokaci...',
    'fetching_location': 'Ana samun wuri...',
    'nearest_pharmacy': 'kantin magani mafi kusa',
    'to': 'zuwa',
    
    // Info Cards (Hausa)
    'welcome_message': 'Barka da zuwa PharmaSeA',
    'find_medicines': 'Nemo magunguna a kusa da ku',
    'fast_delivery': 'Isar da sauri da aminci',
    'learn_more': 'Koyi karin bayani',
    'get_started': 'Fara',
    'shop_now': 'Sayi yanzu',
    'order_now': 'Yi oda yanzu',
    'browse_catalog': 'Duba magunguna',
    'special_offer': 'Tayin na musamman',
    'limited_time': 'Tayin na ɗan lokaci',
    
    // Orders page (Hausa)
    'orders_page_orders': 'Oda',
    'orders_all': 'Duka',
    'pending': 'Ana jira',
    'processing': 'Ana aiki',
    'fulfilled': 'An gama',
    'cancelled': 'An soke',
    'no_orders_yet': 'Babu oda tukuna.',
    'order_number': 'Oda #',
    'orders_customer': 'Abokin ciniki',
    'orders_items': 'Abubuwa',
    'orders_total': 'Duka',
    'orders_status': 'Matsayi',
    'orders_see_more': 'Duba karin',
    'orders_see_less': 'Duba kadan',
    'more_items': 'kari',
    'reveal_number': 'Nuna lambar',
    'please_sign_in_continue': 'Ka shigar da sunan don ci gaba',
    'sign_in_sign_up': 'Shiga / Yi rajista',
    'qty': 'Adadi',
    
    // Messages page (Hausa)
    'my_conversations': 'Tattaunawa\nNa',
    'search_chats': 'Nemo tattaunawa',
    'no_conversations_yet': 'Babu tattaunawa tukuna.',
    'no_messages_yet': 'Babu saƙonni tukuna.',
    
    // Cart page (Hausa)
    'your_cart_is_empty': 'Kayar ku babu komai.',
    'remove': 'Cire',
    'subtotal': 'Ƙaramin jimla',
    'delivery_fee': 'Kuɗin isar da kaya',
    'proceed_to_checkout': 'Ci gaba zuwa biyan kuɗi',
    'order_summary': 'Taƙaitaccen oda',
    'delivery_details': 'Bayanan isar da kaya',
    'delivery_address': 'Adireshin isar da kaya',
    'phone_number': 'Lambar waya',
    'email_optional': 'Imel (Ba dole ba)',
    'enter_delivery_address': 'Shigar da adireshin isar da kaya',
    'enter_phone_number': 'Shigar da lambar waya',
    'enter_email_address': 'Shigar da adireshin imel',
    'use_current_location': 'Yi amfani da wurin yanzu',
    'continue_to_payment': 'Ci gaba zuwa biyan kuɗi',
    'payment_method': 'Hanyar biyan kuɗi',
    'pay_on_delivery': 'Biya lokacin isar da kaya',
    'pay_with_cash_delivery': 'Biya da kuɗi lokacin da oda ya zo',
    'online_payment': 'Biyan kuɗi a yanar gizo',
    'pay_with_card': 'Biya da kati, canja wurin banki, ko USSD',
    'pay_with_card_bank_ussd': 'Biya da kati, canja wurin banki, ko USSD',
    'pay_with_cash_on_delivery': 'Biya da kuɗi lokacin da oda ya zo',
    'use_your_health_insurance': 'Yi amfani da inshorar lafiya',
    'pay_with_insurance': 'Biya da inshora',
    'use_health_insurance': 'Yi amfani da inshorar lafiya',
    'coming_soon': 'Yana zuwa nan ba da jimawa ba',
    'total_amount': 'Dukkanin adadin',
    'pay_now': 'Biya yanzu',
    'place_order': 'Yi oda',
    'decrease_quantity': 'Rage yawan',
    'increase_quantity': 'Ƙara yawan',
    'order_placement_failed': 'Yin oda ya kasa',
    'order_placed_delivery': 'An yi oda cikin nasara! Za ku biya lokacin isar da kaya.',
    'payment_successful': 'Biyan kuɗi ya yi nasara! An yi odar ku.',
    'checkout_failed': 'Biyan kuɗi ya kasa. Da fatan za a sake gwadawa.',
    
    // Profile page (Hausa)
    'my_profile': 'Bayanin Kaina',
    'pharmacy_profile': 'Bayanin Kantin Magani',
    'edit_profile': 'Gyara Bayanin',
    'view': 'Duba',
    'open': 'Buɗe',
    'name': 'Suna',
    'phone_number_profile': 'Lambar Waya',
    'address_profile': 'Adireshi',
    'password': 'Kalmar sirri',
    'items_in_cart': 'Abubuwa a cikin kaya',
    'profile_active_chats': 'Tattaunawa masu aiki',
    'saved_items': 'Abubuwa da aka ajiye',
    'drugs_bought': 'Magungunan da aka saya',
    'all_drugs_bought': 'Dukan magungunan da aka saya',
    'my_saved_items': 'Abubuwan da na ajiye',
    'profile_products': 'Kayayyaki',
    'vendors': 'Masu sayarwa',
    'no_products_saved': 'Babu kayayyaki da aka ajiye',
    'start_adding_products': 'Fara ƙara kayayyakin da kuke so!',
    'no_vendors_bookmarked': 'Babu masu sayarwa da aka yi alamar',
    'bookmark_vendors': 'Yi alamar masu sayarwan da kuke so!',
    'log_out': 'Fita',
    'search_placeholder_profile': 'Nemi takardar likita, oda, magunguna...',
    'prescriptions': 'Takardar likita',
    'orders_profile': 'Oda',
    'drugs': 'Magunguna',
    'all_results': 'Duka',
    'times': 'lokuta',
    'bought': 'da aka saya',
    'no_search_results': 'Babu sakamakon',
    'try_different_search': 'Gwada kalmar nema daban',
    
    // Settings
    'general': 'Gabaɗaya',
    'appearance': 'Bayyanar',
    'language_region': 'Harshe da Yanki',
    'privacy_security': 'Sirri da Tsaro',
    'accessibility': 'Samun dama',
    'app_language': 'Harshen app',
    
    // VendorProfile page (Hausa)
    'vendor_profile': 'Bayanin Mai sayarwa',
    'products_by': 'Kayayyaki da',
    'vendor': 'Mai sayarwa',
    'of': 'daga',
    'no_products_found_search': 'Babu kayayyakin da aka samu da suka dace da binciken ku.',
    'no_products_yet': 'Babu kayayyaki tukuna.',
    'customers_only_chat': 'Abokan ciniki ne kawai za su iya fara tattaunawa da kantin magani.',
    'could_not_start_chat': 'Ba za a iya fara zaren tattaunawa ba.',
    'pharmacy_report': 'Rahoton kantin magani',
    'field': 'Fili',
    'value': 'Kima',
    'pharmacy': 'Kantin magani',
    'email': 'Imel',
    'address': 'Adireshi',
    'phone': 'Waya',
    'product_name': 'Sunan kaya',
    'category': 'Nau\'i',
    'stock': 'Ajiya',
    'sku': 'SKU',
    'vendor_price': 'Farashi',
    'order_id': 'ID oda',
    'customer': 'Abokin ciniki',
    'status': 'Matsayi',
    'date': 'Kwanan wata',
    'vendor_products': 'Kayayyaki',
    'add_to_bookmarks': 'Saka a cikin alamomi',
    'remove_from_bookmarks': 'Cire daga alamomi',
    'search_by_name_category_sku': 'Nema da suna, nau\'i, ko SKU...',
    'view_results': 'Duba sakamakon',
    'clear': 'Share',
    
    // PharmacyMap page (Hausa)
    'nearby_pharmacies': 'Kantunan Magani Kusa',
    'pharmacies_found_near_you': '{count} an samu kusa da kai',
    'loading_location': 'Ana samun wuri...',
    'filter_pharmacies': 'Tace kantunan magani',
    'pharmacies_found_near_you_detailed': 'Kantunan magani {count} an samu kusa da kai',
    'your_location': 'Wurin ka',
    'getting_your_location': 'Ana samun wurin ka...',
    'location_access_needed': 'Ana bukatar samun dama ga wuri',
    'allow_location_access_etas': 'Ka ba da izinin samun wuri don daidaitaccen lokaci',
    'enable_location_services': 'Kunna sabis na wuri don ganin kantunan magani kusa',
    'search_pharmacies': 'Nemi kantunan magani...',
    'no_pharmacies_found': 'Ba a sami kantunan magani ba',
    'keyboard_navigation_hint': 'Yi amfani da ↑↓ maballin tuƙi, Enter don zaɓa, Esc don rufewa',
    'distance': 'Nisa',
    'within_5km': 'A cikin 5km',
    'within_10km': 'A cikin 10km',
    'within_20km': 'A cikin 20km',
    'you_are_here': 'Kana nan',
    'pharmacy_locations': 'Wuraren Kantunan Magani',
    'pharmacies_sorted_by_distance': 'Kantunan magani {count} • An jera bisa nisa',
    'selected': 'An zaɓa',
    'calculating': 'Ana lissafi...',
    'closest': 'Mafi kusa',
    'get_directions': 'Samu Jagora',
    'call': 'Kira',
    'call_pharmacy': 'Kira kantin magani',
    'view_products': 'Duba Kayayyaki',
    'search_results': 'Sakamakon Bincike',
    'all_pharmacies': 'Dukan Kantunan Magani',
    'pharmacies_found_count': '{count} an samu',
    'no_pharmacies_found_search': 'Ba a sami kantunan magani da suka dace da binciken ku ba',
    'no_pharmacies_found_general': 'Ba a sami kantunan magani ba',
    'try_adjusting_search': 'Gwada gyara kalmomin binciken ku',
    'try_adjusting_location': 'Gwada gyara wurin ku ko ku sake dubawa daga baya',
    'clear_search': 'Share bincike',

    // ChatThread page (Hausa)
    'today': 'Yau',
    'yesterday': 'Jiya',
    'sent': 'An aiko',
    'delivered': 'An kai',
    'read': 'An karanta',
    'prescription_created': 'An ƙirƙiri sabon takardar magani.',
    'drug_inquiry': 'Ina son sanin ƙarin game da wannan magani {productName}{priceText}.',
    'call_pharmacy_title': 'Kira {pharmacy}',
    'no_phone_number': 'Babu lambar waya',
    'actions': 'Ayyuka',
    'create_prescription': 'Ƙirƙiri Takardar Magani',
    'view_prescription_history': 'Duba Tarihin Takardar Magani',
    'load_more_messages': 'Ɗauko ƙarin saƙonnin {count}',
    'start_conversation': 'Fara tattaunawar ku',
    'message_placeholder': 'Saƙo',
    'attachments_coming_soon': 'Abubuwan haɗi suna zuwa nan ba da jimawa ba',

    // Dashboard page (Hausa)
    'my_dashboard': 'Dashboard Na',
    'overview': 'Taƙaitaccen Bayani',
    'top_products': 'Manyan Kayayyaki',
    'best_sellers': 'Mafi Sayarwa',
    'no_sales_data': 'Babu bayanan tallace-tallace har yanzu',
    'start_selling_message': 'Fara sayar da kayayyaki don ganin mafi kyawun ku',
    'units_sold': 'Raka\'o {count} da aka sayar',
    'units': 'raka\'o',
    'total_products': 'Jimillar Kayayyaki',
    'total_orders': 'Jimillar Oda',
    'total_revenue': 'Jimillar Kudaden Shiga',
    'active_customers': 'Abokan Ciniki Masu Aiki',
    'this_month': 'Wannan Wata',
    'avg_order_value': 'Matsakaicin Darajar Oda',
    'pending_orders': 'Oda Da Ake Jira',
    'awaiting': 'Ana jira',
    'low_stock_items': 'Kayayyakin Da Suka Rage',
    'need_restock': 'Bukata Sake Cikawa',
    'orders_this_month': 'Oda Na Wannan Wata',
    'no_comparison': 'Babu kwatance',
    'pending_reviews': 'Sharhi Da Ake Jira',
    'need_response': 'Bukatar Amsa',
    'recent_reviews': 'Sharhi Na Baya-bayan Nan',
    'last_24h': 'Sa\'o 24 da suka gabata',
    'low_stock_alert': 'Sanarwar Karancin Kaya',
    'items_need_restocking': 'Kaya {count} na bukatar sake cikawa',
    'inventory_tip': 'Duba ajiyar ku don guje wa rashin shahararru kayayyaki',
    
    // Dashboard Components (Hausa)
    'recent_messages': 'Saƙonnin Baya-bayan Nan',
    'no_recent_messages': 'Babu saƙonnin baya-bayan nan.',
    'no_recent_reviews': 'Babu sharhi na baya-bayan nan',
    'new_reviews_appear_here': 'Sabbin sharhin abokan ciniki za su bayyana a nan',
    'by_customer': 'ta {customerName}',
    'needs_response': 'Bukatar Amsa',
    'view_more_reviews': 'Duba ƙarin sharhi {count}',
    'revenue_analytics': 'Nazarin Kudaden Shiga',
    'by_month': 'Ta Wata',
    'by_year': 'Ta Shekara',
    'month_number': 'Wata {number}',
    'no_revenue_data': 'Babu bayanan kudaden shiga',
    'start_selling_revenue': 'Fara sayarwa don ganin nazarin kudaden shiga',
    'best_performing_period': 'Lokaci Mafi Kyau {period}',
    'month_label': 'Wata',
    'year_label': 'Shekara',
    'sales_trends': 'Hanyoyin Tallace-tallace',
    'last_6_months': 'Watannin 6 da suka gabata',
    'no_sales_trend_data': 'Babu bayanan hanyoyin tallace-tallace.',
    'orders_count': 'Oda {count}',
    
    // Reviews Management (Hausa)
    'reviews_management': 'Gudanar da Sharhi',
    'filters_sort': 'Tacewa da Jeri',
    'total_reviews': 'Jimillar Sharhi',
    'responded': 'An Amsa',
    'avg_rating': 'Matsakaicin Daraja',
    'positive_reviews': 'Mai Kyau (4+ ⭐)',
    'product': 'Kaya',
    'all_products': 'Dukan Kayayyaki',
    'sort_by': 'Jera Ta',
    'newest_first': 'Sabo Da Farko',
    'oldest_first': 'Tsoho Da Farko',
    'highest_rating': 'Mafi Girman Daraja',
    'lowest_rating': 'Mafi Ƙarancin Daraja',
    'filter_by': 'Tacewa Ta',
    'all_reviews': 'Dukan Sharhi',
    'positive_4_stars': 'Mai Kyau (4+ tauraro)',
    'negative_1_2_stars': 'Marar Kyau (1-2 tauraro)',
    'no_reviews_found': 'Ba a sami sharhi ba',
    'no_reviews_yet_message': 'Har yanzu ba ku da sharhi. Ƙarfafa abokan ciniki su bar sharhi ta hanyar samar da kyakkyawan sabis da bin diddigin sadarwa!',
    'no_reviews_match_filters': 'Babu sharhi da ya dace da taushirinku na yanzu. Gwada daidaita ka\'idodin binciken ku.',
    'medicine': 'Magani',
    'reviewed_by': 'An yi sharhi ta',
    'verified': 'An Tabbatar',
    'people_found_helpful': 'Mutane {count} sun sami wannan yana da amfani',
    'your_response': 'Amsarku',
    'cancel_response': 'Soke Amsa',
    'respond_to_review': 'Amsa ga Sharhi',
    'write_thoughtful_response': 'Rubuta amsa mai tunani ga wannan sharhi...',
    'submit_response': 'Tura Amsa',
    'response_submitted_success': 'An tura amsa cikin nasara!',
    'response_submit_failed': 'An kasa tura amsa. Da fatan za a sake gwadawa.',
    'loading_reviews': 'Ana ɗaukar sharhinku...',
    'loading_please_wait': 'Da fatan ku jira yayin da muke ɗaukar bayananku',
    
    // My Prescriptions Section (Hausa)
    'my_prescriptions': 'Takardun Magani Na',
    'add_to_calendar': 'Saka a Kalanda',
    'no_prescriptions_found': 'Ba a sami takardar magani ba.',
    'see_more_count': 'Duba ƙari ({count})',
    'see_less': 'Duba kaɗan',
    'time_to_take_medicine': 'Lokaci ya yi na shan {drugName}',
    'take_medicine': 'Sha {drugName}',
    'dosage_frequency': 'Adadin: {dosage} ({frequency})',
    
    // Profile sections (Hausa)
    'my_activity': 'Ayyukan Na',
    'profile_sections_active_chats': 'Tattaunawa Masu Aiki',
    'storefront_preview': 'Kallaren Kantin',
    'inventory': 'Ajiya',
    'products_sold': 'Kayayyaki Da Aka Sayar',
    
    // Products section translations (Hausa)
    'no_products_yet': 'Har yanzu babu kayayyaki. Yi amfani da maballin da ke sama don ƙara ko loda da yawa.',
    'edit_product': 'Gyara Kayayyaki',
    'product_image': 'Hoton Kayayyaki',
    'image_url_placeholder': 'URL hoto (ko zaɓi fayil da ke ƙasa)',
    'product_description': 'Bayanin Kayayyaki',
    'enter_product_description': 'Shigar da bayanin kayayyaki',
    'confirm_delete_product': 'Kana da tabbas kana son share wannan abu?',
    
    // Product Detail page translations (Hausa)
    'customer_reviews': 'Sharhin Abokan Ciniki',
    'loading_reviews': 'Ana loda sharhi…',
    'no_reviews_yet': 'Har yanzu babu sharhi. Ka zama na farko da ya ba da sharhi!',
    'pharmacy_response': 'Amsar {pharmacyName}',
    'message_vendor': 'Aika Saƙo zuwa Dillali',
    'call_to_order': 'Kira don Yin Oda',
    'your_name': 'Sunan Ka',
    
    // Settings (Hausa)
    'swipe_navigation': 'Kewayawa ta Shafawa',
    'data_saver_mode': 'Yanayin Adana Bayanai',
    'read_receipts': 'Takardar Karatu',
    'theme': 'Jigo',
    'font_size': 'Girman Rubutu',
    'app_language': 'Harshen Manhaja'
  },
  
  ig: {
    // General UI (Igbo)
    'home': 'Ụlọ',
    'cart': 'Ngwa ahịa',
    'messages': 'Ozi',
    'orders': 'Ịtụ',
    'settings': 'Nhazi',
    'notifications': 'Ọkwa',
    'search': 'Chọọ',
    'back': 'Laghachi azụ',
    'continue': 'Gaa n\'ihu',
    'save': 'Chekwaa',
    'cancel': 'Kagbuo',
    'delete': 'Hichapụ',
    'edit': 'Dezie',
    'loading': 'Na-ebu...',
    'profile': 'Profaili',
    
    // Product/Shopping (Igbo)
    'add_to_cart': 'Tinye na ngwa ahịa',
    'buy_now': 'Zụọ ugbu a',
    'price': 'Ọnụ ahịa',
    'out_of_stock': 'Agwụla',
    'in_stock': 'Dị n\'ụlọ ahịa',
    'product_description': 'Nkọwa ngwaahịa',
    'product_unavailable': 'Ngwaahịa adịghị. Biko nwaa ọzọ.',
    
    // Homepage (Igbo)
    'hello': 'Ndewo',
    'friend': 'Enyi',
    'search_placeholder': 'Chọọ ọgwụ, ụlọ ọgwụ',
    'new_arrivals': 'Ndị ọhụrụ',
    'view_all': 'lee niile',
    'popular_products': 'Ọgwụ ndị ama ama',
    'all_new_products': 'Ọgwụ ọhụrụ niile',
    'load_more': 'Buo karịa',
    'new': 'Ọhụrụ',
    'close': 'Mechie',
    'please_sign_in': 'Biko banye',
    'your_pharmacy_location': 'Ọnọdụ ụlọ ọgwụ gị',
    'location_services': 'Ọrụ ọnọdụ',
    'calculating_eta': 'Na-agbako oge...',
    'fetching_location': 'Na-eweta ọnọdụ...',
    'nearest_pharmacy': 'ụlọ ọgwụ kacha nso',
    'to': 'gaa',
    
    // Info Cards (Igbo)
    'welcome_message': 'Nnọọ na PharmaSeA',
    'find_medicines': 'Chọta ọgwụ ndị dị gị nso',
    'fast_delivery': 'Nnyefe ọsọ ọsọ na ntụkwasị obi',
    'learn_more': 'Mụtakwuo ihe',
    'get_started': 'Malite',
    'shop_now': 'Zụọ ugbu a',
    'order_now': 'Nye ọtụtụ ugbu a',
    'browse_catalog': 'Lelee ọgwụ ndị anyị nwere',
    'special_offer': 'Onyinye pụrụ iche',
    'limited_time': 'Onyinye nwa oge',
    
    // Orders page (Igbo)
    'orders': 'Ịtụ',
    'all': 'Niile',
    'pending': 'Na-echere',
    'processing': 'Na-arụ ọrụ',
    'fulfilled': 'Emezula',
    'cancelled': 'Akagbuola',
    'no_orders_yet': 'Enwebeghị ịtụ ọ bụla.',
    'order_number': 'Ịtụ #',
    'customer': 'Onye ahịa',
    'items': 'Ihe ndị',
    'total': 'Mkpokọta',
    'status': 'Ọnọdụ',
    'see_more': 'Hụkwuo',
    'see_less': 'Hụ nke nta',
    'more_items': 'karịa',
    'reveal_number': 'Gosi nọmba',
    'please_sign_in_continue': 'Biko banye ịga n\'ihu',
    'sign_in_sign_up': 'Banye / Debanye aha',
    'qty': 'Ọnụọgụgụ',
    
    // Messages page (Igbo)
    'my_conversations': 'Mkparịta ụka\nM',
    'search_chats': 'Chọọ mkparịta ụka',
    'no_conversations_yet': 'Enwebeghị mkparịta ụka ọ bụla.',
    'no_messages_yet': 'Enwebeghị ozi ọ bụla.',
    
    // Cart page (Igbo)
    'your_cart_is_empty': 'Ngwa ahịa gị adịghị.',
    'remove': 'Wepụ',
    'subtotal': 'Obere mkpokọta',
    'delivery_fee': 'Ego nnyefe',
    'proceed_to_checkout': 'Gaa n\'ịkwụ ụgwọ',
    'order_summary': 'Nchịkọta ịtụ',
    'delivery_details': 'Nkọwa nnyefe',
    'delivery_address': 'Adress nnyefe',
    'phone_number': 'Nọmba ekwentị',
    'email_optional': 'Ịmeelụ (Nhọrọ)',
    'enter_delivery_address': 'Tinye adreesị nnyefe',
    'enter_phone_number': 'Tinye nọmba ekwentị',
    'enter_email_address': 'Tinye adreesị ịmeelụ',
    'use_current_location': 'Jiri ebe dị ugbu a',
    'continue_to_payment': 'Gaa n\'ịkwụ ụgwọ',
    'payment_method': 'Ụzọ ịkwụ ụgwọ',
    'pay_on_delivery': 'Kwụọ mgbe nnyefe',
    'pay_with_cash_delivery': 'Kwụọ ego mgbe ịtụ ruru',
    'online_payment': 'Ịkwụ ụgwọ n\'ịntanetị',
    'pay_with_card': 'Kwụọ na kaadị, mbufe ego banki, ma ọ bụ USSD',
    'pay_with_card_bank_ussd': 'Kwụọ na kaadị, mbufe ego banki, ma ọ bụ USSD',
    'pay_with_cash_on_delivery': 'Kwụọ ego mgbe ịtụ ruru',
    'use_your_health_insurance': 'Jiri mkpuchi ahụ ike gị',
    'pay_with_insurance': 'Kwụọ na mkpuchi',
    'use_health_insurance': 'Jiri mkpuchi ahụ ike gị',
    'coming_soon': 'Na-abịa n\'oge na-adịghị anya',
    'total_amount': 'Mkpokọta ego',
    'pay_now': 'Kwụọ ugbu a',
    'place_order': 'Nye ịtụ',
    'decrease_quantity': 'Belata ọnụọgụgụ',
    'increase_quantity': 'Mee ka ọnụọgụgụ mụbaa',
    'order_placement_failed': 'Inyefe ịtụ dara',
    'order_placed_delivery': 'Enyela ịtụ nke ọma! Ị ga-akwụ ụgwọ mgbe nnyefe.',
    'payment_successful': 'Ịkwụ ụgwọ gara nke ọma! Enyela ịtụ gị.',
    'checkout_failed': 'Ịkwụ ụgwọ dara. Biko nwaa ọzọ.',
    
    // Profile page (Igbo)
    'my_profile': 'Profaịlụ M',
    'pharmacy_profile': 'Profaịlụ Ụlọ Ọgwụ',
    'edit_profile': 'Dezie Profaịlụ',
    'view': 'Lee',
    'open': 'Meghe',
    'phone_number_profile': 'Nọmba Ekwentị',
    'address_profile': 'Adrees',
    'password': 'Okwu nzuzo',
    'items_in_cart': 'Ihe ndị dị na ngwa ahịa',
    'active_chats': 'Mkparịta ụka na-arụ ọrụ',
    'saved_items': 'Ihe ndị echekwala',
    'drugs_bought': 'Ọgwụ ndị azụtala',
    'all_drugs_bought': 'Ọgwụ niile ezutala',
    'my_saved_items': 'Ihe ndị m chekwara',
    'products': 'Ngwaahịa',
    'vendors': 'Ndị na-ere',
    'no_products_saved': 'Enweghị ngwaahịa echekwara',
    'start_adding_products': 'Malite itinye ngwaahịa ị hụrụ n\'anya!',
    'no_vendors_bookmarked': 'Enweghị ndị na-ere akara akara',
    'bookmark_vendors': 'Kaa ndị na-ere ị hụrụ n\'anya akara!',
    'search_placeholder_profile': 'Chọọ ọgwụ, ịtụ, ọgwụ...',
    'prescriptions': 'Ọgwụ',
    'orders_profile': 'Ịtụ',
    'drugs': 'Ọgwụ',
    'all_results': 'Niile',
    'times': 'ugboro',
    'bought': 'azụtara',
    'no_search_results': 'Enweghị nsonaazụ',
    
    // Settings
    'app_language': 'Asụsụ ngwa',
    
    // VendorProfile page (Igbo)
    'vendor_profile': 'Profaịlụ Onye na-ere',
    'products_by': 'Ngwaahịa site na',
    'vendor': 'Onye na-ere',
    'of': 'n\'ime',
    'no_products_found_search': 'Achọtaghị ngwaahịa ọ bụla dakọtara na nchọgharị gị.',
    'no_products_yet': 'Enwebeghị ngwaahịa ọ bụla.',
    'customers_only_chat': 'Ọ bụ naanị ndị ahịa nwere ike ịmalite mkparịta ụka na ụlọ ọgwụ.',
    'could_not_start_chat': 'Enweghị ike ịmalite mkparịta ụka.',
    'pharmacy_report': 'Akụkọ ụlọ ọgwụ',
    'field': 'Ogige',
    'value': 'Uru',
    'pharmacy': 'Ụlọ ọgwụ',
    'email': 'Email',
    'address': 'Adrees',
    'phone': 'Ekwentị',
    'product_name': 'Aha ngwaahịa',
    'category': 'Ụdị',
    'stock': 'Nchekwa',
    'sku': 'SKU',
    'order_id': 'ID nyere',
    'search_by_name_category_sku': 'Chọọ site na aha, ụdị, ma ọ bụ SKU...',
    'view_results': 'Lee nsonaazụ',
    'clear': 'Hichapụ',
    
    // PharmacyMap page (Igbo)
    'nearby_pharmacies': 'Ụlọ Ọgwụ Ndị Dị Nso',
    'pharmacies_found_near_you': '{count} achọtara nso gị',
    'loading_location': 'Na-ebu ebe...',
    'filter_pharmacies': 'Họrọ ụlọ ọgwụ',
    'pharmacies_found_near_you_detailed': 'Ụlọ ọgwụ {count} achọtara nso gị',
    'your_location': 'Ebe gị',
    'getting_your_location': 'Na-enweta ebe gị...',
    'location_access_needed': 'A chọrọ ohere ebe',
    'allow_location_access_etas': 'Biko kwere ka a nweta ebe maka oge ziri ezi',
    'enable_location_services': 'Mee ka ọrụ ebe rụọ ọrụ ka ị hụ ụlọ ọgwụ ndị dị nso',
    'search_pharmacies': 'Chọọ ụlọ ọgwụ...',
    'no_pharmacies_found': 'Achọtaghị ụlọ ọgwụ ọ bụla',
    'keyboard_navigation_hint': 'Jiri ↑↓ mkpịsị aka ịga ebe, Enter ịhọrọ, Esc imechi',
    'distance': 'Anya',
    'within_5km': 'N\'ime 5km',
    'within_10km': 'N\'ime 10km',
    'within_20km': 'N\'ime 20km',
    'you_are_here': 'Ị nọ ebe a',
    'pharmacy_locations': 'Ebe Ụlọ Ọgwụ Dị',
    'pharmacies_sorted_by_distance': 'Ụlọ ọgwụ {count} • Edobere site na anya',
    'selected': 'Ahọrọla',
    'calculating': 'Na-agbako...',
    'closest': 'Nke kacha nso',
    'get_directions': 'Nweta Nduzi',
    'call_pharmacy': 'Kpọọ ụlọ ọgwụ',
    'view_products': 'Lee Ngwaahịa',
    'search_results': 'Nsonaazụ Ọchụchọ',
    'all_pharmacies': 'Ụlọ Ọgwụ Niile',
    'pharmacies_found_count': '{count} achọtara',
    'no_pharmacies_found_search': 'Achọtaghị ụlọ ọgwụ ọ bụla dakọtara na ọchụchọ gị',
    'no_pharmacies_found_general': 'Achọtaghị ụlọ ọgwụ ọ bụla',
    'try_adjusting_search': 'Gbalịa imezigharị okwu ọchụchọ gị',
    'try_adjusting_location': 'Gbalịa imezigharị ebe gị ma ọ bụ lọghachi azụ mgbe ọzọ',
    'clear_search': 'Hichapụ ọchụchọ',

    // ChatThread page (Igbo)
    'today': 'Taa',
    'yesterday': 'Ụnyaahụ',
    'sent': 'Ezigala',
    'delivered': 'Enyela',
    'read': 'Agụla',
    'prescription_created': 'Emepụtala akwụkwọ ọgwụ ọhụrụ.',
    'drug_inquiry': 'Achọrọ m ịmata karịa gbasara ọgwụ a {productName}{priceText}.',
    'call_pharmacy_title': 'Kpọọ {pharmacy}',
    'no_phone_number': 'Enweghị nọmba ekwentị',
    'actions': 'Omume',
    'create_prescription': 'Mepụta Akwụkwọ Ọgwụ',
    'view_prescription_history': 'Lee Akụkọ Akwụkwọ Ọgwụ',
    'load_more_messages': 'Bulie ozi {count} ọzọ',
    'start_conversation': 'Malite mkparịta ụka gị',
    'message_placeholder': 'Ozi',
    'attachments_coming_soon': 'Ihe ndị agbakwunyere na-abịa ngwa ngwa',

    // Dashboard page (Igbo)
    'my_dashboard': 'Dashboard M',
    'overview': 'Nchikọta',
    'top_products': 'Ngwaahịa Kachasị Elu',
    'best_sellers': 'Ndị Na-ere Kacha Mma',
    'no_sales_data': 'Enwebeghị data ire ere',
    'start_selling_message': 'Malite ire ngwaahịa iji hụ ndị kacha arụ ọrụ',
    'units_sold': 'Nkeji {count} erere',
    'units': 'nkeji',
    'total_products': 'Mkpokọta Ngwaahịa',
    'total_orders': 'Mkpokọta Ọrder',
    'total_revenue': 'Mkpokọta Ego Mbata',
    'active_customers': 'Ndị Ahịa Na-arụ Ọrụ',
    'this_month': 'Ọnwa A',
    'avg_order_value': 'Uru Ọrder Nkezi',
    'pending_orders': 'Ọrder Na-echere',
    'awaiting': 'Na-echere',
    'low_stock_items': 'Ngwaahịa Dị Ntakịrị',
    'need_restock': 'Kwesịrị Itinyeghachi',
    'orders_this_month': 'Ọrder Ọnwa A',
    'no_comparison': 'Enweghị ntụnyere',
    'pending_reviews': 'Nyocha Na-echere',
    'need_response': 'Kwesịrị Nzaghachi',
    'recent_reviews': 'Nyocha Nso Nso A',
    'last_24h': 'Awa 24 gara aga',
    'low_stock_alert': 'Ọkwa Ngwaahịa Dị Ntakịrị',
    'items_need_restocking': 'Ihe {count} kwesịrị itinyeghachi',
    'inventory_tip': 'Lelee ngwaahịa gị iji zere ịgwụ ngwaahịa ndị a ma ama',
    
    // Dashboard Components (Igbo)
    'recent_messages': 'Ozi Nso Nso A',
    'no_recent_messages': 'Enweghị ozi nso nso a.',
    'no_recent_reviews': 'Enweghị nyocha nso nso a',
    'new_reviews_appear_here': 'Nyocha ndị ahịa ọhụrụ ga-apụta ebe a',
    'by_customer': 'site n\'aka {customerName}',
    'needs_response': 'Kwesịrị Nzaghachi',
    'view_more_reviews': 'Lee nyocha {count} ọzọ',
    'revenue_analytics': 'Nyocha Ego Mbata',
    'by_month': 'Site n\'Ọnwa',
    'by_year': 'Site n\'Afọ',
    'month_number': 'Ọnwa {number}',
    'no_revenue_data': 'Enweghị data ego mbata',
    'start_selling_revenue': 'Malite ire iji hụ nyocha ego mbata gị',
    'best_performing_period': 'Oge Kacha Mma {period}',
    'month_label': 'Ọnwa',
    'year_label': 'Afọ',
    'sales_trends': 'Ụzọ Ire Ahịa',
    'last_6_months': 'Ọnwa 6 gara aga',
    'no_sales_trend_data': 'Enweghị data ụzọ ire ahịa.',
    'orders_count': 'Ọrder {count}',
    
    // Reviews Management (Igbo)
    'reviews_management': 'Nlekọta Nyocha',
    'filters_sort': 'Nzacha na Nhazi',
    'total_reviews': 'Mkpokọta Nyocha',
    'responded': 'Azaghachila',
    'avg_rating': 'Nkezi Ogo',
    'positive_reviews': 'Nke Ọma (4+ ⭐)',
    'product': 'Ngwaahịa',
    'all_products': 'Ngwaahịa Niile',
    'sort_by': 'Hazie Site Na',
    'newest_first': 'Ọhụrụ Mbụ',
    'oldest_first': 'Ochie Mbụ',
    'highest_rating': 'Ogo Kacha Elu',
    'lowest_rating': 'Ogo Kacha Ala',
    'filter_by': 'Zọpụta Site Na',
    'all_reviews': 'Nyocha Niile',
    'positive_4_stars': 'Nke Ọma (4+ kpakpando)',
    'negative_1_2_stars': 'Nke Ọjọọ (1-2 kpakpando)',
    'no_reviews_found': 'Achọtaghị nyocha ọ bụla',
    'no_reviews_yet_message': 'I nwebeghị nyocha ọ bụla. Gbaa ndị ahịa ume ka ha hapụ nyocha site n\'inye ọrụ magburu onwe ya na nkwurịta okwu na-esote!',
    'no_reviews_match_filters': 'Enweghị nyocha dabara na nzacha gị ugbu a. Gbalịa ime mgbanwe na njirisi ọchụchọ gị.',
    'medicine': 'Ọgwụ',
    'reviewed_by': 'Nyochara site na',
    'verified': 'Enyochala',
    'people_found_helpful': 'Ndị mmadụ {count} chọpụtara na nke a bara uru',
    'your_response': 'Nzaghachi Gị',
    'cancel_response': 'Kagbuo Nzaghachi',
    'respond_to_review': 'Zaghachi na Nyocha',
    'write_thoughtful_response': 'Dee nzaghachi nwere uche na nyocha a...',
    'submit_response': 'Ziga Nzaghachi',
    'response_submitted_success': 'E zigara nzaghachi nke ọma!',
    'response_submit_failed': 'E nweghị ike izipu nzaghachi. Biko nwaghachi ọzọ.',
    'loading_reviews': 'Na-ebu nyocha gị...',
    'loading_please_wait': 'Biko chere ka anyị na-eweta data gị',
    
    // My Prescriptions Section (Igbo)
    'my_prescriptions': 'Akwụkwọ Ọgwụ M',
    'add_to_calendar': 'Tinye na Kalenda',
    'no_prescriptions_found': 'Achọtaghị akwụkwọ ọgwụ ọ bụla.',
    'see_more_count': 'Lee ọzọ ({count})',
    'see_less': 'Lee ntakịrị',
    'time_to_take_medicine': 'Oge ịṅụ {drugName}',
    'take_medicine': 'Ṅụọ {drugName}',
    'dosage_frequency': 'Ọnụọgụgụ: {dosage} ({frequency})',
    
    // Profile sections (Igbo)
    'my_activity': 'Ọrụ M',
    'active_chats': 'Mkparịta Ụka Na-arụ Ọrụ',
    'storefront_preview': 'Nlele Ụlọ Ahịa',
    'inventory': 'Nchekwa Ngwaahịa',
    'products_sold': 'Ngwaahịa E Rere',
    
    // Products section translations (Igbo)
    'no_products_yet': 'Enwebeghị ngwaahịa. Jiri bọtịnụ ndị dị n\'elu tinye ma ọ bụ bulite ọtụtụ.',
    'edit_product': 'Dezie Ngwaahịa',
    'product_image': 'Foto Ngwaahịa',
    'image_url_placeholder': 'URL foto (ma ọ bụ họrọ faịlụ n\'okpuru)',
    'product_description': 'Nkọwa Ngwaahịa',
    'enter_product_description': 'Tinye nkọwa ngwaahịa',
    'confirm_delete_product': 'Ị ji n\'ezie chọọ ihichapụ ihe a?',
    
    // Product Detail page translations (Igbo)
    'customer_reviews': 'Nyocha Ndị Ahịa',
    'loading_reviews': 'Na-ebu nyocha…',
    'no_reviews_yet': 'Enwebeghị nyocha. Bụrụ onye mbụ nyochaa!',
    'pharmacy_response': 'Nzaghachi {pharmacyName}',
    'message_vendor': 'Zigara Onye Na-ere Ahịa Ozi',
    'call_to_order': 'Kpọọ Maka Ịzọ',
    'your_name': 'Aha Gị',
    
    // Settings (Igbo)
    'swipe_navigation': 'Ịgagharị Site na Ifufe',
    'data_saver_mode': 'Ọnọdụ Nchekwa Data',
    'read_receipts': 'Akwụkwọ Nnata Ọgụgụ',
    'theme': 'Isiokwu',
    'font_size': 'Nha Mkpụrụedemede',
    'app_language': 'Asụsụ Ngwa'
  },
  
  fr: {
    // General UI (French)
    'home': 'Accueil',
    'cart': 'Panier',
    'messages': 'Messages',
    'orders': 'Commandes',
    'settings': 'Paramètres',
    'notifications': 'Notifications',
    'search': 'Rechercher',
    'back': 'Retour',
    'continue': 'Continuer',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'delete': 'Supprimer',
    'edit': 'Modifier',
    'loading': 'Chargement...',
    'profile': 'Profil',
    
    // Product/Shopping (French)
    'add_to_cart': 'Ajouter au panier',
    'buy_now': 'Acheter maintenant',
    'price': 'Prix',
    'out_of_stock': 'Rupture de stock',
    'in_stock': 'En stock',
    'product_description': 'Description du produit',
    'product_unavailable': 'Produit indisponible. Veuillez réessayer.',
    
    // Homepage (French)
    'hello': 'Bonjour',
    'friend': 'Ami',
    'search_placeholder': 'Rechercher médicaments, pharmacies',
    'new_arrivals': 'Nouveautés',
    'view_all': 'voir tout',
    'popular_products': 'Produits populaires',
    'all_new_products': 'Tous les nouveaux produits',
    'load_more': 'Charger plus',
    'new': 'Nouveau',
    'close': 'Fermer',
    'please_sign_in': 'Veuillez vous connecter',
    'your_pharmacy_location': 'Emplacement de votre pharmacie',
    'location_services': 'Services de localisation',
    'calculating_eta': 'Calcul du temps...',
    'fetching_location': 'Obtention de la localisation...',
    'nearest_pharmacy': 'pharmacie la plus proche',
    'to': 'vers',
    
    // Info Cards (French)
    'welcome_message': 'Bienvenue à PharmaSeA',
    'find_medicines': 'Trouvez des médicaments près de chez vous',
    'fast_delivery': 'Livraison rapide et fiable',
    'learn_more': 'En savoir plus',
    'get_started': 'Commencer',
    'shop_now': 'Acheter maintenant',
    'order_now': 'Commander maintenant',
    'browse_catalog': 'Parcourir le catalogue',
    'special_offer': 'Offre spéciale',
    'limited_time': 'Offre à durée limitée',
    
    // Orders page (French)
    'orders': 'Commandes',
    'all': 'Tout',
    'pending': 'En attente',
    'processing': 'En cours',
    'fulfilled': 'Livré',
    'cancelled': 'Annulé',
    'no_orders_yet': 'Aucune commande pour le moment.',
    'order_number': 'Commande #',
    'customer': 'Client',
    'items': 'Articles',
    'total': 'Total',
    'status': 'Statut',
    'see_more': 'Voir plus',
    'see_less': 'Voir moins',
    'more_items': 'de plus',
    'reveal_number': 'Révéler le numéro',
    'please_sign_in_continue': 'Veuillez vous connecter pour continuer',
    'sign_in_sign_up': 'Se connecter / S\'inscrire',
    'qty': 'Qté',
    
    // Messages page (French)
    'my_conversations': 'Mes\nConversations',
    'search_chats': 'Rechercher des conversations',
    'no_conversations_yet': 'Aucune conversation pour le moment.',
    'no_messages_yet': 'Aucun message pour le moment.',
    
    // Cart page (French)
    'cart': 'Panier',
    'your_cart_is_empty': 'Votre panier est vide.',
    'remove': 'Supprimer',
    'subtotal': 'Sous-total',
    'delivery_fee': 'Frais de livraison',
    'total': 'Total',
    'proceed_to_checkout': 'Procéder au paiement',
    'order_summary': 'Résumé de commande',
    'items': 'Articles',
    'delivery_details': 'Détails de livraison',
    'delivery_address': 'Adresse de livraison',
    'phone_number': 'Numéro de téléphone',
    'email_optional': 'E-mail (Facultatif)',
    'enter_delivery_address': 'Entrer l\'adresse de livraison',
    'enter_phone_number': 'Entrer le numéro de téléphone',
    'enter_email_address': 'Entrer l\'adresse e-mail',
    'use_current_location': 'Utiliser la localisation actuelle',
    'continue_to_payment': 'Continuer vers le paiement',
    'payment_method': 'Mode de paiement',
    'pay_on_delivery': 'Payer à la livraison',
    'pay_with_cash_delivery': 'Payer en espèces à la livraison',
    'online_payment': 'Paiement en ligne',
    'pay_with_card': 'Payer par carte, virement bancaire, ou USSD',
    'pay_with_card_bank_ussd': 'Payer par carte, virement bancaire, ou USSD',
    'pay_with_cash_on_delivery': 'Payer en espèces à la livraison',
    'use_your_health_insurance': 'Utiliser votre assurance santé',
    'pay_with_insurance': 'Payer avec l\'assurance',
    'use_health_insurance': 'Utiliser votre assurance santé',
    'coming_soon': 'Bientôt disponible',
    'total_amount': 'Montant total',
    'pay_now': 'Payer maintenant',
    'place_order': 'Passer commande',
    'decrease_quantity': 'Diminuer la quantité',
    'increase_quantity': 'Augmenter la quantité',
    'order_placement_failed': 'Échec de la commande',
    'order_placed_delivery': 'Commande passée avec succès! Vous paierez à la livraison.',
    'payment_successful': 'Paiement réussi! Votre commande a été passée.',
    'checkout_failed': 'Paiement échoué. Veuillez réessayer.',
    
    // Profile page (French)
    'my_profile': 'Mon Profil',
    'pharmacy_profile': 'Profil de la Pharmacie',
    'edit_profile': 'Modifier le Profil',
    'edit': 'Modifier',
    'save': 'Enregistrer',
    'cancel': 'Annuler',
    'close': 'Fermer',
    'view': 'Voir',
    'open': 'Ouvrir',
    'name': 'Nom',
    'phone_number_profile': 'Numéro de Téléphone',
    'address_profile': 'Adresse',
    'password': 'Mot de passe',
    'items_in_cart': 'Articles dans le panier',
    'active_chats': 'Conversations actives',
    'saved_items': 'Articles sauvegardés',
    'drugs_bought': 'Médicaments achetés',
    'all_drugs_bought': 'Tous les médicaments achetés',
    'my_saved_items': 'Mes articles sauvegardés',
    'products': 'Produits',
    'vendors': 'Vendeurs',
    'no_products_saved': 'Aucun produit sauvegardé',
    'start_adding_products': 'Commencez à ajouter des produits que vous aimez!',
    'no_vendors_bookmarked': 'Aucun vendeur mis en signet',
    'bookmark_vendors': 'Mettez en signet les vendeurs que vous aimez!',
    'log_out': 'Déconnexion',
    'search_placeholder_profile': 'Rechercher prescriptions, commandes, médicaments...',
    'prescriptions': 'Prescriptions',
    'orders_profile': 'Commandes',
    'drugs': 'Médicaments',
    'all_results': 'Tous',
    'times': 'fois',
    'bought': 'acheté',
    'no_search_results': 'Aucun résultat trouvé',
    'try_different_search': 'Essayez un terme de recherche différent',
    
    // Settings
    'general': 'Général',
    'appearance': 'Apparence',
    'language_region': 'Langue et Région',
    'privacy_security': 'Confidentialité et Sécurité',
    'accessibility': 'Accessibilité',
    'app_language': 'Langue de l\'application',
    
    // VendorProfile page (French)
    'vendor_profile': 'Profil du Vendeur',
    'products_by': 'Produits par',
    'vendor': 'Vendeur',
    'of': 'sur',
    'no_products_found_search': 'Aucun produit trouvé correspondant à votre recherche.',
    'no_products_yet': 'Aucun produit pour le moment.',
    'customers_only_chat': 'Seuls les clients peuvent entamer une conversation avec une pharmacie.',
    'could_not_start_chat': 'Impossible de démarrer le fil de discussion.',
    'pharmacy_report': 'Rapport de pharmacie',
    'field': 'Champ',
    'value': 'Valeur',
    'pharmacy': 'Pharmacie',
    'email': 'Email',
    'address': 'Adresse',
    'phone': 'Téléphone',
    'product_name': 'Nom du produit',
    'category': 'Catégorie',
    'stock': 'Stock',
    'sku': 'SKU',
    'price': 'Prix',
    'order_id': 'ID commande',
    'customer': 'Client',
    'status': 'Statut',
    'date': 'Date',
    'products': 'Produits',
    'add_to_bookmarks': 'Ajouter aux favoris',
    'remove_from_bookmarks': 'Supprimer des favoris',
    'search_by_name_category_sku': 'Rechercher par nom, catégorie ou SKU...',
    'view_results': 'Voir les résultats',
    'clear': 'Effacer',
    
    // PharmacyMap page (French)
    'nearby_pharmacies': 'Pharmacies à Proximité',
    'pharmacies_found_near_you': '{count} trouvées près de vous',
    'loading_location': 'Chargement de la localisation...',
    'filter_pharmacies': 'Filtrer les pharmacies',
    'pharmacies_found_near_you_detailed': '{count} pharmacies trouvées près de vous',
    'your_location': 'Votre localisation',
    'getting_your_location': 'Obtention de votre localisation...',
    'location_access_needed': 'Accès à la localisation nécessaire',
    'allow_location_access_etas': 'Veuillez autoriser l\'accès à la localisation pour des horaires précis',
    'enable_location_services': 'Activez les services de localisation pour voir les pharmacies à proximité',
    'search_pharmacies': 'Rechercher des pharmacies...',
    'no_pharmacies_found': 'Aucune pharmacie trouvée',
    'try_different_search': 'Essayez un terme de recherche différent',
    'name': 'Nom',
    'address': 'Adresse',
    'keyboard_navigation_hint': 'Utilisez ↑↓ pour naviguer, Entrée pour sélectionner, Échap pour fermer',
    'distance': 'Distance',
    'all': 'Tout',
    'within_5km': 'Dans les 5km',
    'within_10km': 'Dans les 10km',
    'within_20km': 'Dans les 20km',
    'you_are_here': 'Vous êtes ici',
    'pharmacy_locations': 'Emplacements des Pharmacies',
    'pharmacies_sorted_by_distance': '{count} pharmacies • Triées par distance',
    'pharmacy': 'Pharmacie',
    'selected': 'Sélectionné',
    'calculating': 'Calcul en cours...',
    'closest': 'Le plus proche',
    'get_directions': 'Obtenir un Itinéraire',
    'call': 'Appeler',
    'call_pharmacy': 'Appeler la pharmacie',
    'view_products': 'Voir les Produits',
    'search_results': 'Résultats de Recherche',
    'all_pharmacies': 'Toutes les Pharmacies',
    'pharmacies_found_count': '{count} trouvées',
    'no_pharmacies_found_search': 'Aucune pharmacie trouvée correspondant à votre recherche',
    'no_pharmacies_found_general': 'Aucune pharmacie trouvée',
    'try_adjusting_search': 'Essayez d\'ajuster vos termes de recherche',
    'try_adjusting_location': 'Essayez d\'ajuster votre localisation ou revenez plus tard',
    'clear_search': 'Effacer la recherche',

    // ChatThread page (French)
    'today': 'Aujourd\'hui',
    'yesterday': 'Hier',
    'sent': 'Envoyé',
    'delivered': 'Livré',
    'read': 'Lu',
    'customer': 'Client',
    'pharmacy': 'Pharmacie',
    'prescription_created': 'Une nouvelle ordonnance a été créée.',
    'drug_inquiry': 'Je souhaiterais en savoir plus sur ce médicament {productName}{priceText}.',
    'call': 'Appeler',
    'call_pharmacy_title': 'Appeler {pharmacy}',
    'no_phone_number': 'Pas de numéro de téléphone',
    'actions': 'Actions',
    'create_prescription': 'Créer une Ordonnance',
    'view_prescription_history': 'Voir l\'Historique des Ordonnances',
    'load_more_messages': 'Charger {count} messages de plus',
    'start_conversation': 'Commencez votre conversation',
    'message_placeholder': 'Message',
    'attachments_coming_soon': 'Pièces jointes bientôt disponibles',

    // Dashboard page (French)
    'my_dashboard': 'Mon Tableau de Bord',
    'overview': 'Aperçu',
    'top_products': 'Produits Populaires',
    'best_sellers': 'Meilleures Ventes',
    'no_sales_data': 'Aucune donnée de vente pour le moment',
    'start_selling_message': 'Commencez à vendre des produits pour voir vos meilleures performances',
    'units_sold': '{count} unités vendues',
    'units': 'unités',
    'total_products': 'Total Produits',
    'total_orders': 'Total Commandes',
    'total_revenue': 'Chiffre d\'Affaires Total',
    'active_customers': 'Clients Actifs',
    'this_month': 'Ce Mois',
    'avg_order_value': 'Valeur Moyenne Commande',
    'pending_orders': 'Commandes En Attente',
    'awaiting': 'En attente',
    'low_stock_items': 'Articles En Rupture',
    'need_restock': 'À Réapprovisionner',
    'orders_this_month': 'Commandes Ce Mois',
    'no_comparison': 'Pas de comparaison',
    'pending_reviews': 'Avis En Attente',
    'need_response': 'Nécessitent Réponse',
    'recent_reviews': 'Avis Récents',
    'last_24h': 'Dernières 24h',
    'low_stock_alert': 'Alerte Stock Faible',
    'items_need_restocking': '{count} article{plural} nécessitent un réapprovisionnement',
    'inventory_tip': 'Vérifiez votre inventaire pour éviter les ruptures de produits populaires',
    
    // Dashboard Components (French)
    'recent_messages': 'Messages Récents',
    'no_recent_messages': 'Aucun message récent.',
    'no_recent_reviews': 'Aucun avis récent',
    'new_reviews_appear_here': 'Les nouveaux avis clients apparaîtront ici',
    'view_all': 'Voir Tout',
    'by_customer': 'par {customerName}',
    'needs_response': 'Nécessitent Réponse',
    'view_more_reviews': 'Voir {count} avis de plus',
    'revenue_analytics': 'Analyse des Revenus',
    'total': 'Total',
    'by_month': 'Par Mois',
    'by_year': 'Par Année',
    'month_number': 'Mois {number}',
    'no_revenue_data': 'Aucune donnée de revenus disponible',
    'start_selling_revenue': 'Commencez à vendre pour voir vos analyses de revenus',
    'best_performing_period': 'Meilleure Période {period}',
    'month_label': 'Mois',
    'year_label': 'Année',
    'sales_trends': 'Tendances des Ventes',
    'last_6_months': '6 derniers mois',
    'no_sales_trend_data': 'Aucune donnée de tendance des ventes.',
    'orders_count': '{count} commande{plural}',
    
    // Reviews Management (French)
    'reviews_management': 'Gestion des Avis',
    'filters_sort': 'Filtres et Tri',
    'total_reviews': 'Total des Avis',
    'responded': 'Répondu',
    'avg_rating': 'Note Moyenne',
    'positive_reviews': 'Positifs (4+ ⭐)',
    'product': 'Produit',
    'all_products': 'Tous les Produits',
    'sort_by': 'Trier par',
    'newest_first': 'Plus Récents d\'Abord',
    'oldest_first': 'Plus Anciens d\'Abord',
    'highest_rating': 'Note la Plus Haute',
    'lowest_rating': 'Note la Plus Basse',
    'filter_by': 'Filtrer par',
    'all_reviews': 'Tous les Avis',
    'positive_4_stars': 'Positifs (4+ étoiles)',
    'negative_1_2_stars': 'Négatifs (1-2 étoiles)',
    'no_reviews_found': 'Aucun avis trouvé',
    'no_reviews_yet_message': 'Vous n\'avez pas encore d\'avis. Encouragez les clients à laisser des avis en fournissant un excellent service et une communication de suivi !',
    'no_reviews_match_filters': 'Aucun avis ne correspond à vos filtres actuels. Essayez d\'ajuster vos critères de recherche.',
    'medicine': 'Médicament',
    'reviewed_by': 'Avis par',
    'verified': 'Vérifié',
    'people_found_helpful': '{count} personnes ont trouvé cela utile',
    'your_response': 'Votre Réponse',
    'cancel_response': 'Annuler la Réponse',
    'respond_to_review': 'Répondre à l\'Avis',
    'write_thoughtful_response': 'Rédigez une réponse réfléchie à cet avis...',
    'submit_response': 'Envoyer la Réponse',
    'response_submitted_success': 'Réponse envoyée avec succès !',
    'response_submit_failed': 'Échec de l\'envoi de la réponse. Veuillez réessayer.',
    'loading_reviews': 'Chargement de vos avis...',
    'loading_please_wait': 'Veuillez patienter pendant que nous récupérons vos données',
    
    // My Prescriptions Section (French)
    'my_prescriptions': 'Mes Ordonnances',
    'add_to_calendar': 'Ajouter au Calendrier',
    'no_prescriptions_found': 'Aucune ordonnance trouvée.',
    'see_more_count': 'Voir plus ({count})',
    'see_less': 'Voir moins',
    'time_to_take_medicine': 'Il est temps de prendre {drugName}',
    'take_medicine': 'Prendre {drugName}',
    'dosage_frequency': 'Dosage: {dosage} ({frequency})',
    
    // Profile sections (French)
    'my_activity': 'Mon Activité',
    'active_chats': 'Chats Actifs',
    'storefront_preview': 'Aperçu de la Vitrine',
    'inventory': 'Inventaire',
    'products_sold': 'Produits Vendus',
    
    // Products section translations (French)
    'no_products_yet': 'Pas encore de produits. Utilisez les boutons ci-dessus pour ajouter ou télécharger en masse.',
    'edit_product': 'Modifier le Produit',
    'product_image': 'Image du Produit',
    'image_url_placeholder': 'URL de l\'image (ou choisissez un fichier ci-dessous)',
    'product_description': 'Description du Produit',
    'enter_product_description': 'Entrez la description du produit',
    'confirm_delete_product': 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    'yes_delete': 'Oui, Supprimer',
    'log_out': 'Se Déconnecter',
    
    // Product Detail page translations (French)
    'customer_reviews': 'Avis Clients',
    'loading_reviews': 'Chargement des avis…',
    'no_reviews_yet': 'Pas encore d\'avis. Soyez le premier à donner votre avis !',
    'pharmacy_response': 'Réponse de {pharmacyName}',
    'message_vendor': 'Contacter le Vendeur',
    'call_to_order': 'Appeler pour Commander',
    'your_name': 'Votre Nom',
    'your_review_optional': 'Votre avis... (optionnel)',
    
    // Settings (French)
    'general': 'Général',
    'appearance': 'Apparence',
    'language_region': 'Langue et Région',
    'privacy_security': 'Confidentialité et Sécurité',
    'accessibility': 'Accessibilité',
    'swipe_navigation': 'Navigation par Balayage',
    'data_saver_mode': 'Mode Économie de Données',
    'read_receipts': 'Accusés de Lecture',
    'theme': 'Thème',
    'font_size': 'Taille de Police',
    'app_language': 'Langue de l\'Application'
  }
};

export const useTranslation = () => {
  const { getSetting } = useSettings();
  const currentLanguage = getSetting(SETTINGS_KEYS.LANGUAGE) || 'en';

  // t supports optional interpolation vars: t(key, fallback?, vars?)
  const t = useMemo(() => {
    return (key, fallback = key, vars = {}) => {
      const raw = translations[currentLanguage]?.[key] || translations['en']?.[key] || fallback;
      if (!raw || typeof raw !== 'string') return raw;
      // replace {name} placeholders with provided vars
      return raw.replace(/\{(\w+)\}/g, (_, name) => {
        if (vars && Object.prototype.hasOwnProperty.call(vars, name)) {
          return String(vars[name]);
        }
        return `{${name}}`;
      });
    };
  }, [currentLanguage]);

  return { t, currentLanguage };
};

export const LanguageProvider = ({ children }) => {
  const { t, currentLanguage } = useTranslation();
  
  return (
    <LanguageContext.Provider value={{ t, currentLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
